# Tables

In [1]:
# datascience
from datascience import *
import numpy as np

In [2]:
# polars
import polars as pl
from IPython.display import display

## Arrays

In [3]:
# datascience
a = make_array(5, 6, 7, 8)

In [4]:
# polars
a_pl = pl.Series('values', [5, 6, 7, 8])

In [5]:
a + 1

array([6, 7, 8, 9])

In [6]:
a * 2

array([10, 12, 14, 16])

In [7]:
a + a

array([10, 12, 14, 16])

* Array methods (for this class, just `.item()`)
* Built-in array functions
* NumPy array functions

In [8]:
(a + a).item(2)

14

In [9]:
sum(a)

26

In [10]:
len(a)

4

In [11]:
sum(a) / len(a)

6.5

In [12]:
# datascience
np.average(a)

6.5

In [13]:
# polars
(a_pl).mean()

6.5

In [14]:
# datascience
np.cumsum(a)

array([ 5, 11, 18, 26])

In [15]:
# polars
(a_pl).cum_sum()

shape: (4,)
Series: 'values' [i64]
[
	5
	11
	18
	26
]

## Ranges ##

In [16]:
# datascience
make_array(0, 1, 2, 3, 4, 5, 6)

array([0, 1, 2, 3, 4, 5, 6])

In [17]:
# polars
pl.Series('values', [0, 1, 2, 3, 4, 5, 6])

shape: (7,)
Series: 'values' [i64]
[
	0
	1
	2
	3
	4
	5
	6
]

In [18]:
# datascience
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [19]:
# polars
pl.int_range(7, eager=True)

shape: (7,)
Series: 'literal' [i64]
[
	0
	1
	2
	3
	4
	5
	6
]

In [20]:
# datascience
np.arange(5, 11)

array([ 5,  6,  7,  8,  9, 10])

In [21]:
# polars
pl.int_range(5, 11, eager=True)

shape: (6,)
Series: 'literal' [i64]
[
	5
	6
	7
	8
	9
	10
]

In [22]:
# datascience
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [23]:
# polars
pl.int_range(0, 20, 2, eager=True)

shape: (10,)
Series: 'literal' [i64]
[
	0
	2
	4
	6
	8
	10
	12
	14
	16
	18
]

In [24]:
# datascience
np.arange(0, 21, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [25]:
# polars
pl.int_range(0, 21, 2, eager=True)

shape: (11,)
Series: 'literal' [i64]
[
	0
	2
	4
	6
	8
	…
	12
	14
	16
	18
	20
]

In [26]:
# datascience
np.arange(0, 1, 0.1)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9])

In [27]:
# polars
pl.linear_space(0, (1) - (0.1), int(round(((1) - (0)) / (0.1))), closed='both', eager=True)

shape: (10,)
Series: 'literal' [f64]
[
	0.0
	0.1
	0.2
	0.3
	0.4
	0.5
	0.6
	0.7
	0.8
	0.9
]

## Columns of Tables are Arrays ##

In [28]:
# datascience
nba_2026 = Table.read_table('nba_salaries.csv').where('season', 2026)
warriors = nba_2026.where('team', 'Golden State Warriors')

In [29]:
# polars
nba_2026_pl = pl.read_csv('nba_salaries.csv').filter((pl.col('season') == (2026)))
warriors_pl = nba_2026_pl.filter((pl.col('team') == ('Golden State Warriors')))

In [30]:
warriors

rank | name               | position | team                  | salary   | season
1    | Stephen Curry      | PG       | Golden State Warriors | 59606817 | 2026
9    | Jimmy Butler III   | SF       | Golden State Warriors | 54126450 | 2026
57   | Kristaps Porzingis | C        | Golden State Warriors | 30731707 | 2026
69   | Draymond Green     | PF       | Golden State Warriors | 25892857 | 2026
149  | Moses Moody        | SG       | Golden State Warriors | 11574074 | 2026
236  | Al Horford         | C        | Golden State Warriors | 5685000  | 2026
284  | Brandin Podziemski | SG       | Golden State Warriors | 3687960  | 2026
305  | De'Anthony Melton  | PG       | Golden State Warriors | 3080921  | 2026
377  | Gary Payton II     | SG       | Golden State Warriors | 2296274  | 2026
401  | Gui Santos         | PF       | Golden State Warriors | 2221677  | 2026
... (3 rows omitted)

In [31]:
# datascience
warriors.select('salary')

salary
59606817
54126450
30731707
25892857
11574074
5685000
3687960
3080921
2296274
2221677
... (3 rows omitted)

In [32]:
# polars
warriors_pl.select('salary')

shape: (13, 1)
┌──────────┐
│ salary   │
│ ---      │
│ i64      │
╞══════════╡
│ 59606817 │
│ 54126450 │
│ 30731707 │
│ 25892857 │
│ 11574074 │
│ …        │
│ 2296274  │
│ 2221677  │
│ 1755198  │
│ 1272870  │
│ 857804   │
└──────────┘

In [33]:
# datascience
warriors.column('salary')

array([59606817, 54126450, 30731707, 25892857, 11574074,  5685000,
        3687960,  3080921,  2296274,  2221677,  1755198,  1272870,   857804])

In [34]:
# polars
warriors_pl.get_column('salary')

shape: (13,)
Series: 'salary' [i64]
[
	59606817
	54126450
	30731707
	25892857
	11574074
	…
	2296274
	2221677
	1755198
	1272870
	857804
]

**Discuss**: What was the average salary among players on the warriors in the (2025-)2026 season? Start with the `warriors` table.

In [35]:
# datascience
np.average(warriors.column('salary'))

15599200.692307692

In [36]:
# polars
(warriors_pl.get_column('salary')).mean()

15599200.692307692

How does that average compare to the New York Knicks?

In [37]:
# datascience
knicks = nba_2026.where('team', 'New York Knicks')

In [38]:
# polars
knicks_pl = nba_2026_pl.filter((pl.col('team') == ('New York Knicks')))

In [39]:
# datascience
np.average(warriors.column('salary')) - np.average(knicks.column('salary'))

1650110.4923076928

In [40]:
# polars
(warriors_pl.get_column('salary')).mean() - (knicks_pl.get_column('salary')).mean()

1650110.4923076928

## Create a table from columns

In [41]:
# datascience
streets = make_array('Bancroft', 'Durant', 'Channing', 'Haste')
streets

array(['Bancroft', 'Durant', 'Channing', 'Haste'],
      dtype='<U8')

In [42]:
# polars
streets_pl = pl.Series('values', ['Bancroft', 'Durant', 'Channing', 'Haste'])
streets_pl

shape: (4,)
Series: 'values' [str]
[
	"Bancroft"
	"Durant"
	"Channing"
	"Haste"
]

In [43]:
# datascience
Table()

In [44]:
# polars
pl.DataFrame()

shape: (0, 0)
┌┐
╞╡
└┘

In [45]:
# datascience
southside = Table().with_column('Street', streets)
southside

Street
Bancroft
Durant
Channing
Haste

In [46]:
# polars
southside_pl = pl.DataFrame([
    (streets_pl).alias('Street')
])
southside_pl

shape: (4, 1)
┌──────────┐
│ Street   │
│ ---      │
│ str      │
╞══════════╡
│ Bancroft │
│ Durant   │
│ Channing │
│ Haste    │
└──────────┘

In [47]:
# datascience
southside.with_column('Blocks from campus', np.arange(4))

Street   | Blocks from campus
Bancroft | 0
Durant   | 1
Channing | 2
Haste    | 3

In [48]:
# polars
southside_pl.with_columns((pl.int_range(4, eager=True)).alias('Blocks from campus'))

shape: (4, 2)
┌──────────┬────────────────────┐
│ Street   ┆ Blocks from campus │
│ ---      ┆ ---                │
│ str      ┆ i64                │
╞══════════╪════════════════════╡
│ Bancroft ┆ 0                  │
│ Durant   ┆ 1                  │
│ Channing ┆ 2                  │
│ Haste    ┆ 3                  │
└──────────┴────────────────────┘

In [49]:
# datascience
Table().with_columns(
    'Street', streets,
    'Blocks from campus', np.arange(4)
)

Street   | Blocks from campus
Bancroft | 0
Durant   | 1
Channing | 2
Haste    | 3

In [50]:
# polars
pl.DataFrame([
    (streets_pl).alias('Street'),
    (pl.int_range(4, eager=True)).alias('Blocks from campus')
])

shape: (4, 2)
┌──────────┬────────────────────┐
│ Street   ┆ Blocks from campus │
│ ---      ┆ ---                │
│ str      ┆ i64                │
╞══════════╪════════════════════╡
│ Bancroft ┆ 0                  │
│ Durant   ┆ 1                  │
│ Channing ┆ 2                  │
│ Haste    ┆ 3                  │
└──────────┴────────────────────┘

In [51]:
# datascience
# how might I get "Channing" from this table?
southside = southside.with_column('Blocks from campus', np.arange(4))
southside.where("Street", "Channing").column("Street").item(0)

'Channing'

In [52]:
# polars
# how might I get "Channing" from this table?
southside_pl = southside_pl.with_columns((pl.int_range(4, eager=True)).alias('Blocks from campus'))
southside_pl.filter((pl.col("Street") == ("Channing"))).get_column("Street").item(0)

'Channing'

## W.E.B. Du Bois was a data scientist!

[W.E.B. Du Bois - Wikipedia](https://en.wikipedia.org/wiki/W._E._B._Du_Bois)

[Data from Library of Congress](https://www.loc.gov/pictures/collection/anedub/item/2013650354/)

In [53]:
# datascience
du_bois = Table.read_table('du_bois.csv')
du_bois

CLASS         | ACTUAL AVERAGE | RENT | FOOD | CLOTHES | TAXES | OTHER | STATUS
100-200       | 139.1          | 0.19 | 0.43 | 0.28    | 0.001 | 0.099 | POOR
200-300       | 249.45         | 0.22 | 0.47 | 0.23    | 0.04  | 0.04  | POOR
300-400       | 335.66         | 0.23 | 0.43 | 0.18    | 0.045 | 0.115 | FAIR
400-500       | 433.82         | 0.18 | 0.37 | 0.15    | 0.055 | 0.245 | FAIR
500-750       | 547            | 0.13 | 0.31 | 0.17    | 0.05  | 0.34  | COMFORTABLE
750-1000      | 880            | 0    | 0.37 | 0.19    | 0.08  | 0.36  | COMFORTABLE
1000 and over | 1125           | 0    | 0.29 | 0.16    | 0.045 | 0.505 | WELL-TO-DO

In [54]:
# polars
du_bois_pl = pl.read_csv('du_bois.csv')
du_bois_pl

shape: (7, 8)
┌───────────────┬────────────────┬──────┬──────┬─────────┬───────┬───────┬─────────────┐
│ CLASS         ┆ ACTUAL AVERAGE ┆ RENT ┆ FOOD ┆ CLOTHES ┆ TAXES ┆ OTHER ┆ STATUS      │
│ ---           ┆ ---            ┆ ---  ┆ ---  ┆ ---     ┆ ---   ┆ ---   ┆ ---         │
│ str           ┆ f64            ┆ f64  ┆ f64  ┆ f64     ┆ f64   ┆ f64   ┆ str         │
╞═══════════════╪════════════════╪══════╪══════╪═════════╪═══════╪═══════╪═════════════╡
│ 100-200       ┆ 139.1          ┆ 0.19 ┆ 0.43 ┆ 0.28    ┆ 0.001 ┆ 0.099 ┆ POOR        │
│ 200-300       ┆ 249.45         ┆ 0.22 ┆ 0.47 ┆ 0.23    ┆ 0.04  ┆ 0.04  ┆ POOR        │
│ 300-400       ┆ 335.66         ┆ 0.23 ┆ 0.43 ┆ 0.18    ┆ 0.045 ┆ 0.115 ┆ FAIR        │
│ 400-500       ┆ 433.82         ┆ 0.18 ┆ 0.37 ┆ 0.15    ┆ 0.055 ┆ 0.245 ┆ FAIR        │
│ 500-750       ┆ 547.0          ┆ 0.13 ┆ 0.31 ┆ 0.17    ┆ 0.05  ┆ 0.34  ┆ COMFORTABLE │
│ 750-1000      ┆ 880.0          ┆ 0.0  ┆ 0.37 ┆ 0.19    ┆ 0.08  ┆ 0.36  ┆ COMFORTABLE │
│ 1000 and over ┆ 1125.0         ┆ 0.0  ┆ 0.29 ┆ 0.16    ┆ 0.045 ┆ 0.505 ┆ WELL-TO-DO  │
└───────────────┴────────────────┴──────┴──────┴─────────┴───────┴───────┴─────────────┘

In [55]:
# datascience
du_bois.column('ACTUAL AVERAGE')

array([  139.1 ,   249.45,   335.66,   433.82,   547.  ,   880.  ,  1125.  ])

In [56]:
# polars
du_bois_pl.get_column('ACTUAL AVERAGE')

shape: (7,)
Series: 'ACTUAL AVERAGE' [f64]
[
	139.1
	249.45
	335.66
	433.82
	547.0
	880.0
	1125.0
]

In [57]:
# datascience
du_bois.column('FOOD')

array([ 0.43,  0.47,  0.43,  0.37,  0.31,  0.37,  0.29])

In [58]:
# polars
du_bois_pl.get_column('FOOD')

shape: (7,)
Series: 'FOOD' [f64]
[
	0.43
	0.47
	0.43
	0.37
	0.31
	0.37
	0.29
]

In [59]:
# datascience
# how to get the average amount spent on food (by income bracket)?
du_bois.column('ACTUAL AVERAGE') * du_bois.column('FOOD')

array([  59.813 ,  117.2415,  144.3338,  160.5134,  169.57  ,  325.6   ,
        326.25  ])

In [60]:
# polars
# how to get the average amount spent on food (by income bracket)?
du_bois_pl.get_column('ACTUAL AVERAGE') * du_bois_pl.get_column('FOOD')

shape: (7,)
Series: 'ACTUAL AVERAGE' [f64]
[
	59.813
	117.2415
	144.3338
	160.5134
	169.57
	325.6
	326.25
]

In [61]:
# datascience
# how to include this amount in table?
food_dollars = du_bois.column('ACTUAL AVERAGE') * du_bois.column('FOOD')
du_bois.with_columns('Food $', food_dollars)

CLASS         | ACTUAL AVERAGE | RENT | FOOD | CLOTHES | TAXES | OTHER | STATUS      | Food $
100-200       | 139.1          | 0.19 | 0.43 | 0.28    | 0.001 | 0.099 | POOR        | 59.813
200-300       | 249.45         | 0.22 | 0.47 | 0.23    | 0.04  | 0.04  | POOR        | 117.241
300-400       | 335.66         | 0.23 | 0.43 | 0.18    | 0.045 | 0.115 | FAIR        | 144.334
400-500       | 433.82         | 0.18 | 0.37 | 0.15    | 0.055 | 0.245 | FAIR        | 160.513
500-750       | 547            | 0.13 | 0.31 | 0.17    | 0.05  | 0.34  | COMFORTABLE | 169.57
750-1000      | 880            | 0    | 0.37 | 0.19    | 0.08  | 0.36  | COMFORTABLE | 325.6
1000 and over | 1125           | 0    | 0.29 | 0.16    | 0.045 | 0.505 | WELL-TO-DO  | 326.25

In [62]:
# polars
# how to include this amount in table?
food_dollars_pl = du_bois_pl.get_column('ACTUAL AVERAGE') * du_bois_pl.get_column('FOOD')
du_bois_pl.with_columns(pl.Series('Food $', food_dollars_pl))

shape: (7, 9)
┌───────────────┬────────────────┬──────┬──────┬───┬───────┬───────┬─────────────┬──────────┐
│ CLASS         ┆ ACTUAL AVERAGE ┆ RENT ┆ FOOD ┆ … ┆ TAXES ┆ OTHER ┆ STATUS      ┆ Food $   │
│ ---           ┆ ---            ┆ ---  ┆ ---  ┆   ┆ ---   ┆ ---   ┆ ---         ┆ ---      │
│ str           ┆ f64            ┆ f64  ┆ f64  ┆   ┆ f64   ┆ f64   ┆ str         ┆ f64      │
╞═══════════════╪════════════════╪══════╪══════╪═══╪═══════╪═══════╪═════════════╪══════════╡
│ 100-200       ┆ 139.1          ┆ 0.19 ┆ 0.43 ┆ … ┆ 0.001 ┆ 0.099 ┆ POOR        ┆ 59.813   │
│ 200-300       ┆ 249.45         ┆ 0.22 ┆ 0.47 ┆ … ┆ 0.04  ┆ 0.04  ┆ POOR        ┆ 117.2415 │
│ 300-400       ┆ 335.66         ┆ 0.23 ┆ 0.43 ┆ … ┆ 0.045 ┆ 0.115 ┆ FAIR        ┆ 144.3338 │
│ 400-500       ┆ 433.82         ┆ 0.18 ┆ 0.37 ┆ … ┆ 0.055 ┆ 0.245 ┆ FAIR        ┆ 160.5134 │
│ 500-750       ┆ 547.0          ┆ 0.13 ┆ 0.31 ┆ … ┆ 0.05  ┆ 0.34  ┆ COMFORTABLE ┆ 169.57   │
│ 750-1000      ┆ 880.0          ┆ 0.0  ┆ 0.37 ┆ … ┆ 0.08  ┆ 0.36  ┆ COMFORTABLE ┆ 325.6    │
│ 1000 and over ┆ 1125.0         ┆ 0.0  ┆ 0.29 ┆ … ┆ 0.045 ┆ 0.505 ┆ WELL-TO-DO  ┆ 326.25   │
└───────────────┴────────────────┴──────┴──────┴───┴───────┴───────┴─────────────┴──────────┘

In [63]:
du_bois

CLASS         | ACTUAL AVERAGE | RENT | FOOD | CLOTHES | TAXES | OTHER | STATUS
100-200       | 139.1          | 0.19 | 0.43 | 0.28    | 0.001 | 0.099 | POOR
200-300       | 249.45         | 0.22 | 0.47 | 0.23    | 0.04  | 0.04  | POOR
300-400       | 335.66         | 0.23 | 0.43 | 0.18    | 0.045 | 0.115 | FAIR
400-500       | 433.82         | 0.18 | 0.37 | 0.15    | 0.055 | 0.245 | FAIR
500-750       | 547            | 0.13 | 0.31 | 0.17    | 0.05  | 0.34  | COMFORTABLE
750-1000      | 880            | 0    | 0.37 | 0.19    | 0.08  | 0.36  | COMFORTABLE
1000 and over | 1125           | 0    | 0.29 | 0.16    | 0.045 | 0.505 | WELL-TO-DO

In [64]:
# datascience
# how to include this amount in table? revisited
du_bois = du_bois.with_columns('Food $', food_dollars)
du_bois

CLASS         | ACTUAL AVERAGE | RENT | FOOD | CLOTHES | TAXES | OTHER | STATUS      | Food $
100-200       | 139.1          | 0.19 | 0.43 | 0.28    | 0.001 | 0.099 | POOR        | 59.813
200-300       | 249.45         | 0.22 | 0.47 | 0.23    | 0.04  | 0.04  | POOR        | 117.241
300-400       | 335.66         | 0.23 | 0.43 | 0.18    | 0.045 | 0.115 | FAIR        | 144.334
400-500       | 433.82         | 0.18 | 0.37 | 0.15    | 0.055 | 0.245 | FAIR        | 160.513
500-750       | 547            | 0.13 | 0.31 | 0.17    | 0.05  | 0.34  | COMFORTABLE | 169.57
750-1000      | 880            | 0    | 0.37 | 0.19    | 0.08  | 0.36  | COMFORTABLE | 325.6
1000 and over | 1125           | 0    | 0.29 | 0.16    | 0.045 | 0.505 | WELL-TO-DO  | 326.25

In [65]:
# polars
# how to include this amount in table? revisited
du_bois_pl = du_bois_pl.with_columns((food_dollars_pl).alias('Food $'))
du_bois_pl

shape: (7, 9)
┌───────────────┬────────────────┬──────┬──────┬───┬───────┬───────┬─────────────┬──────────┐
│ CLASS         ┆ ACTUAL AVERAGE ┆ RENT ┆ FOOD ┆ … ┆ TAXES ┆ OTHER ┆ STATUS      ┆ Food $   │
│ ---           ┆ ---            ┆ ---  ┆ ---  ┆   ┆ ---   ┆ ---   ┆ ---         ┆ ---      │
│ str           ┆ f64            ┆ f64  ┆ f64  ┆   ┆ f64   ┆ f64   ┆ str         ┆ f64      │
╞═══════════════╪════════════════╪══════╪══════╪═══╪═══════╪═══════╪═════════════╪══════════╡
│ 100-200       ┆ 139.1          ┆ 0.19 ┆ 0.43 ┆ … ┆ 0.001 ┆ 0.099 ┆ POOR        ┆ 59.813   │
│ 200-300       ┆ 249.45         ┆ 0.22 ┆ 0.47 ┆ … ┆ 0.04  ┆ 0.04  ┆ POOR        ┆ 117.2415 │
│ 300-400       ┆ 335.66         ┆ 0.23 ┆ 0.43 ┆ … ┆ 0.045 ┆ 0.115 ┆ FAIR        ┆ 144.3338 │
│ 400-500       ┆ 433.82         ┆ 0.18 ┆ 0.37 ┆ … ┆ 0.055 ┆ 0.245 ┆ FAIR        ┆ 160.5134 │
│ 500-750       ┆ 547.0          ┆ 0.13 ┆ 0.31 ┆ … ┆ 0.05  ┆ 0.34  ┆ COMFORTABLE ┆ 169.57   │
│ 750-1000      ┆ 880.0          ┆ 0.0  ┆ 0.37 ┆ … ┆ 0.08  ┆ 0.36  ┆ COMFORTABLE ┆ 325.6    │
│ 1000 and over ┆ 1125.0         ┆ 0.0  ┆ 0.29 ┆ … ┆ 0.045 ┆ 0.505 ┆ WELL-TO-DO  ┆ 326.25   │
└───────────────┴────────────────┴──────┴──────┴───┴───────┴───────┴─────────────┴──────────┘

In [66]:
# datascience
# how to reorder the columns?
du_bois = du_bois.select('CLASS', 'ACTUAL AVERAGE', 'FOOD', 'Food $')
# alternatively..
# du_bois = du_bois.select(0, 1, 2, 3, 8, 4, 5, 6, 7)
du_bois

CLASS         | ACTUAL AVERAGE | FOOD | Food $
100-200       | 139.1          | 0.43 | 59.813
200-300       | 249.45         | 0.47 | 117.241
300-400       | 335.66         | 0.43 | 144.334
400-500       | 433.82         | 0.37 | 160.513
500-750       | 547            | 0.31 | 169.57
750-1000      | 880            | 0.37 | 325.6
1000 and over | 1125           | 0.29 | 326.25

In [67]:
# polars
# how to reorder the columns?
du_bois_pl = du_bois_pl.select('CLASS', 'ACTUAL AVERAGE', 'FOOD', 'Food $')
# alternatively..
# du_bois = du_bois.select(0, 1, 2, 3, 8, 4, 5, 6, 7)
du_bois_pl

shape: (7, 4)
┌───────────────┬────────────────┬──────┬──────────┐
│ CLASS         ┆ ACTUAL AVERAGE ┆ FOOD ┆ Food $   │
│ ---           ┆ ---            ┆ ---  ┆ ---      │
│ str           ┆ f64            ┆ f64  ┆ f64      │
╞═══════════════╪════════════════╪══════╪══════════╡
│ 100-200       ┆ 139.1          ┆ 0.43 ┆ 59.813   │
│ 200-300       ┆ 249.45         ┆ 0.47 ┆ 117.2415 │
│ 300-400       ┆ 335.66         ┆ 0.43 ┆ 144.3338 │
│ 400-500       ┆ 433.82         ┆ 0.37 ┆ 160.5134 │
│ 500-750       ┆ 547.0          ┆ 0.31 ┆ 169.57   │
│ 750-1000      ┆ 880.0          ┆ 0.37 ┆ 325.6    │
│ 1000 and over ┆ 1125.0         ┆ 0.29 ┆ 326.25   │
└───────────────┴────────────────┴──────┴──────────┘

Other things you can do with all tables
* column labels
* number of rows
* number of columns

In [68]:
# datascience
du_bois.labels

('CLASS', 'ACTUAL AVERAGE', 'FOOD', 'Food $')

In [69]:
# polars
du_bois_pl.columns

['CLASS', 'ACTUAL AVERAGE', 'FOOD', 'Food $']

In [70]:
# datascience
du_bois.num_rows

7

In [71]:
# polars
du_bois_pl.height

7

In [72]:
du_bois.num_columns

4

Discussion question approaches: see lecture

In [73]:
# one approach to discussion question

In [74]:
# alternate approach? try your own!