# Tables

In [1]:
# datascience
from datascience import *
import numpy as np

In [2]:
# polars
import polars as pl
from IPython.display import display

## Arrays

In [3]:
# datascience
a = make_array(5, 6, 7, 8)

In [4]:
# polars
a_pl = pl.Series('values', [5, 6, 7, 8])

* Array methods (for this class, just `.item()`)
* Built-in array functions
* NumPy array functions

## Ranges ##

In [5]:
# datascience
make_array(0, 1, 2, 3, 4, 5, 6)

array([0, 1, 2, 3, 4, 5, 6])

In [6]:
# polars
pl.Series('values', [0, 1, 2, 3, 4, 5, 6])

shape: (7,)
Series: 'values' [i64]
[
	0
	1
	2
	3
	4
	5
	6
]

In [7]:
# datascience
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [8]:
# polars
pl.int_range(7, eager=True)

shape: (7,)
Series: 'literal' [i64]
[
	0
	1
	2
	3
	4
	5
	6
]

In [9]:
# datascience
np.arange(5, 11)

array([ 5,  6,  7,  8,  9, 10])

In [10]:
# polars
pl.int_range(5, 11, eager=True)

shape: (6,)
Series: 'literal' [i64]
[
	5
	6
	7
	8
	9
	10
]

In [11]:
# datascience
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
# polars
pl.int_range(0, 20, 2, eager=True)

shape: (10,)
Series: 'literal' [i64]
[
	0
	2
	4
	6
	8
	10
	12
	14
	16
	18
]

In [13]:
# datascience
np.arange(0, 21, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [14]:
# polars
pl.int_range(0, 21, 2, eager=True)

shape: (11,)
Series: 'literal' [i64]
[
	0
	2
	4
	6
	8
	…
	12
	14
	16
	18
	20
]

In [15]:
# datascience
np.arange(0, 1, 0.1)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9])

In [16]:
# polars
pl.linear_space(0, (1) - (0.1), int(round(((1) - (0)) / (0.1))), closed='both', eager=True)

shape: (10,)
Series: 'literal' [f64]
[
	0.0
	0.1
	0.2
	0.3
	0.4
	0.5
	0.6
	0.7
	0.8
	0.9
]

## Columns of Tables are Arrays ##

In [17]:
# datascience
nba_2026 = Table.read_table('nba_salaries.csv').where('season', 2026)
warriors = nba_2026.where('team', 'Golden State Warriors')

In [18]:
# polars
nba_2026_pl = pl.read_csv('nba_salaries.csv').filter((pl.col('season') == (2026)))
warriors_pl = nba_2026_pl.filter((pl.col('team') == ('Golden State Warriors')))

In [19]:
# how to see all 13 players on the team?
warriors

rank | name               | position | team                  | salary   | season
1    | Stephen Curry      | PG       | Golden State Warriors | 59606817 | 2026
9    | Jimmy Butler III   | SF       | Golden State Warriors | 54126450 | 2026
57   | Kristaps Porzingis | C        | Golden State Warriors | 30731707 | 2026
69   | Draymond Green     | PF       | Golden State Warriors | 25892857 | 2026
149  | Moses Moody        | SG       | Golden State Warriors | 11574074 | 2026
236  | Al Horford         | C        | Golden State Warriors | 5685000  | 2026
284  | Brandin Podziemski | SG       | Golden State Warriors | 3687960  | 2026
305  | De'Anthony Melton  | PG       | Golden State Warriors | 3080921  | 2026
377  | Gary Payton II     | SG       | Golden State Warriors | 2296274  | 2026
401  | Gui Santos         | PF       | Golden State Warriors | 2221677  | 2026
... (3 rows omitted)

In [20]:
# datascience
# what is the type of this expression?
warriors.select('salary')

salary
59606817
54126450
30731707
25892857
11574074
5685000
3687960
3080921
2296274
2221677
... (3 rows omitted)

In [21]:
# polars
# what is the type of this expression?
warriors_pl.select('salary')

shape: (13, 1)
┌──────────┐
│ salary   │
│ ---      │
│ i64      │
╞══════════╡
│ 59606817 │
│ 54126450 │
│ 30731707 │
│ 25892857 │
│ 11574074 │
│ …        │
│ 2296274  │
│ 2221677  │
│ 1755198  │
│ 1272870  │
│ 857804   │
└──────────┘

In [22]:
# 1. how to get just the values in the column?
# 2. how to assign it to a name?

In [23]:
# 1. how to get steph curry's salary as a number?
# 2. what happens if he gets 5% more next year?

In [24]:
# what is the total salary payout to the team?

**Discuss**: What was the average salary among players on the warriors in the (2025-)2026 season? Start with the `warriors` table.

In [25]:
# ...(warriors...)

How does that average compare to the New York Knicks?

In [26]:
# datascience
knicks = nba_2026.where('team', 'New York Knicks')
knicks

rank | name               | position | team            | salary   | season
6    | Karl-Anthony Towns | C        | New York Knicks | 54126450 | 2026
27   | OG Anunoby         | PF       | New York Knicks | 39568966 | 2026
46   | Jalen Brunson      | PG       | New York Knicks | 34944001 | 2026
76   | Mikal Bridges      | SF       | New York Knicks | 24900000 | 2026
91   | Josh Hart          | SF       | New York Knicks | 19472240 | 2026
138  | Mitchell Robinson  | C        | New York Knicks | 12954546 | 2026
265  | Jose Alvarado      | PG       | New York Knicks | 4500000  | 2026
270  | Miles McBride      | SG       | New York Knicks | 4333333  | 2026
315  | Pacome Dadiet      | SG       | New York Knicks | 2847600  | 2026
320  | Dillon Jones       | SF       | New York Knicks | 2753280  | 2026
... (5 rows omitted)

In [27]:
# polars
knicks_pl = nba_2026_pl.filter((pl.col('team') == ('New York Knicks')))
knicks_pl

shape: (15, 6)
┌──────┬────────────────────┬──────────┬─────────────────┬──────────┬────────┐
│ rank ┆ name               ┆ position ┆ team            ┆ salary   ┆ season │
│ ---  ┆ ---                ┆ ---      ┆ ---             ┆ ---      ┆ ---    │
│ i64  ┆ str                ┆ str      ┆ str             ┆ i64      ┆ i64    │
╞══════╪════════════════════╪══════════╪═════════════════╪══════════╪════════╡
│ 6    ┆ Karl-Anthony Towns ┆ C        ┆ New York Knicks ┆ 54126450 ┆ 2026   │
│ 27   ┆ OG Anunoby         ┆ PF       ┆ New York Knicks ┆ 39568966 ┆ 2026   │
│ 46   ┆ Jalen Brunson      ┆ PG       ┆ New York Knicks ┆ 34944001 ┆ 2026   │
│ 76   ┆ Mikal Bridges      ┆ SF       ┆ New York Knicks ┆ 24900000 ┆ 2026   │
│ 91   ┆ Josh Hart          ┆ SF       ┆ New York Knicks ┆ 19472240 ┆ 2026   │
│ …    ┆ …                  ┆ …        ┆ …               ┆ …        ┆ …      │
│ 369  ┆ Landry Shamet      ┆ SG       ┆ New York Knicks ┆ 2296274  ┆ 2026   │
│ 370  ┆ Jordan Clarkson    ┆ SG       ┆ New York Knicks ┆ 2296274  ┆ 2026   │
│ 410  ┆ Tyler Kolek        ┆ PG       ┆ New York Knicks ┆ 2191897  ┆ 2026   │
│ 443  ┆ Mohamed Diawara    ┆ SF       ┆ New York Knicks ┆ 1272870  ┆ 2026   │
│ 457  ┆ Jeremy Sochan      ┆ PF       ┆ New York Knicks ┆ 778622   ┆ 2026   │
└──────┴────────────────────┴──────────┴─────────────────┴──────────┴────────┘

In [28]:
# compute the difference in averages

---

## Create a table from columns

In [29]:
# datascience
streets = make_array('Bancroft', 'Durant', 'Channing', 'Haste')
streets

array(['Bancroft', 'Durant', 'Channing', 'Haste'],
      dtype='<U8')

In [30]:
# polars
streets_pl = pl.Series('values', ['Bancroft', 'Durant', 'Channing', 'Haste'])
streets_pl

shape: (4,)
Series: 'values' [str]
[
	"Bancroft"
	"Durant"
	"Channing"
	"Haste"
]

In [31]:
# datascience
Table()

In [32]:
# polars
pl.DataFrame()

shape: (0, 0)
┌┐
╞╡
└┘

In [33]:
# datascience
southside = Table().with_column('Streets', streets)
southside

Streets
Bancroft
Durant
Channing
Haste

In [34]:
# polars
southside_pl = pl.DataFrame([
    (streets_pl).alias('Streets')
])
southside_pl

shape: (4, 1)
┌──────────┐
│ Streets  │
│ ---      │
│ str      │
╞══════════╡
│ Bancroft │
│ Durant   │
│ Channing │
│ Haste    │
└──────────┘

In [35]:
# datascience
southside.with_column('Blocks from campus', np.arange(4))

Streets  | Blocks from campus
Bancroft | 0
Durant   | 1
Channing | 2
Haste    | 3

In [36]:
# polars
southside_pl.with_columns((pl.int_range(4, eager=True)).alias('Blocks from campus'))

shape: (4, 2)
┌──────────┬────────────────────┐
│ Streets  ┆ Blocks from campus │
│ ---      ┆ ---                │
│ str      ┆ i64                │
╞══════════╪════════════════════╡
│ Bancroft ┆ 0                  │
│ Durant   ┆ 1                  │
│ Channing ┆ 2                  │
│ Haste    ┆ 3                  │
└──────────┴────────────────────┘

In [37]:
# datascience
Table().with_columns(
    'Streets', streets,
    'Blocks from campus', np.arange(4)
)

Streets  | Blocks from campus
Bancroft | 0
Durant   | 1
Channing | 2
Haste    | 3

In [38]:
# polars
pl.DataFrame([
    (streets_pl).alias('Streets'),
    (pl.int_range(4, eager=True)).alias('Blocks from campus')
])

shape: (4, 2)
┌──────────┬────────────────────┐
│ Streets  ┆ Blocks from campus │
│ ---      ┆ ---                │
│ str      ┆ i64                │
╞══════════╪════════════════════╡
│ Bancroft ┆ 0                  │
│ Durant   ┆ 1                  │
│ Channing ┆ 2                  │
│ Haste    ┆ 3                  │
└──────────┴────────────────────┘

In [39]:
# how might I get "Channing" from this table?

## W.E.B. Du Bois was a data scientist!

https://en.wikipedia.org/wiki/W._E._B._Du_Bois

In [40]:
# datascience
du_bois = Table.read_table('du_bois.csv')
du_bois

CLASS         | ACTUAL AVERAGE | RENT | FOOD | CLOTHES | TAXES | OTHER | STATUS
100-200       | 139.1          | 0.19 | 0.43 | 0.28    | 0.001 | 0.099 | POOR
200-300       | 249.45         | 0.22 | 0.47 | 0.23    | 0.04  | 0.04  | POOR
300-400       | 335.66         | 0.23 | 0.43 | 0.18    | 0.045 | 0.115 | FAIR
400-500       | 433.82         | 0.18 | 0.37 | 0.15    | 0.055 | 0.245 | FAIR
500-750       | 547            | 0.13 | 0.31 | 0.17    | 0.05  | 0.34  | COMFORTABLE
750-1000      | 880            | 0    | 0.37 | 0.19    | 0.08  | 0.36  | COMFORTABLE
1000 and over | 1125           | 0    | 0.29 | 0.16    | 0.045 | 0.505 | WELL-TO-DO

In [41]:
# polars
du_bois_pl = pl.read_csv('du_bois.csv')
du_bois_pl

shape: (7, 8)
┌───────────────┬────────────────┬──────┬──────┬─────────┬───────┬───────┬─────────────┐
│ CLASS         ┆ ACTUAL AVERAGE ┆ RENT ┆ FOOD ┆ CLOTHES ┆ TAXES ┆ OTHER ┆ STATUS      │
│ ---           ┆ ---            ┆ ---  ┆ ---  ┆ ---     ┆ ---   ┆ ---   ┆ ---         │
│ str           ┆ f64            ┆ f64  ┆ f64  ┆ f64     ┆ f64   ┆ f64   ┆ str         │
╞═══════════════╪════════════════╪══════╪══════╪═════════╪═══════╪═══════╪═════════════╡
│ 100-200       ┆ 139.1          ┆ 0.19 ┆ 0.43 ┆ 0.28    ┆ 0.001 ┆ 0.099 ┆ POOR        │
│ 200-300       ┆ 249.45         ┆ 0.22 ┆ 0.47 ┆ 0.23    ┆ 0.04  ┆ 0.04  ┆ POOR        │
│ 300-400       ┆ 335.66         ┆ 0.23 ┆ 0.43 ┆ 0.18    ┆ 0.045 ┆ 0.115 ┆ FAIR        │
│ 400-500       ┆ 433.82         ┆ 0.18 ┆ 0.37 ┆ 0.15    ┆ 0.055 ┆ 0.245 ┆ FAIR        │
│ 500-750       ┆ 547.0          ┆ 0.13 ┆ 0.31 ┆ 0.17    ┆ 0.05  ┆ 0.34  ┆ COMFORTABLE │
│ 750-1000      ┆ 880.0          ┆ 0.0  ┆ 0.37 ┆ 0.19    ┆ 0.08  ┆ 0.36  ┆ COMFORTABLE │
│ 1000 and over ┆ 1125.0         ┆ 0.0  ┆ 0.29 ┆ 0.16    ┆ 0.045 ┆ 0.505 ┆ WELL-TO-DO  │
└───────────────┴────────────────┴──────┴──────┴─────────┴───────┴───────┴─────────────┘

In [42]:
# datascience
du_bois.column('ACTUAL AVERAGE')

array([  139.1 ,   249.45,   335.66,   433.82,   547.  ,   880.  ,  1125.  ])

In [43]:
# polars
du_bois_pl.get_column('ACTUAL AVERAGE')

shape: (7,)
Series: 'ACTUAL AVERAGE' [f64]
[
	139.1
	249.45
	335.66
	433.82
	547.0
	880.0
	1125.0
]

In [44]:
# datascience
du_bois.column('FOOD')

array([ 0.43,  0.47,  0.43,  0.37,  0.31,  0.37,  0.29])

In [45]:
# polars
du_bois_pl.get_column('FOOD')

shape: (7,)
Series: 'FOOD' [f64]
[
	0.43
	0.47
	0.43
	0.37
	0.31
	0.37
	0.29
]

In [46]:
# how to get the average amount spent on food (by income bracket)?

In [47]:
# how to include this amount in table?

In [48]:
# how to reorder the columns?

Other things you can do with all tables
* column labels
* number of rows
* number of columns

In [49]:
# one approach to discussion question

In [50]:
# alternate approach?