# Lecture 3 Notebook

In [1]:
# datascience
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

In [2]:
# polars
import polars as pl
from IPython.display import display

## Review (and then some)

### Python fundamentals

Python as a calculator:

In [3]:
2 + 9

11

In [4]:
2 * 4

8

In [5]:
# The line below errors
# * 4

In [6]:
2 ** 4

16

In [7]:
# The line below errors 
# 2 * * 4

In [8]:
2/9

0.2222222222222222

Python understands the order of operations!

In [9]:
2 + 3 * 9

29

In [10]:
(2 + 3) * 9

45

In [11]:
-1 - 1 + 2 * (3 * 4 * 5 / 6) ** 3 + 7 + 8 + 12

2025.0

Floating point vs integer representation (more next time)

In [12]:
8

8

In [13]:
64 / 8

8.0

New: Strings!

In [14]:
'hello'

'hello'

In [15]:
'Data 8'

'Data 8'

In [16]:
"hello"

'hello'

In [17]:
# datascience
'I don't ever want to miss class'

SyntaxError: unterminated string literal (detected at line 2) (1714489237.py, line 2)

In [18]:
# polars
'I don't ever want to miss class'

SyntaxError: unterminated string literal (detected at line 2) (736522272.py, line 2)

In [19]:
"I don't ever want to miss class"

"I don't ever want to miss class"

### Names

In [20]:
a = 2

In [21]:
a

2

Names must first be assigned to a value!

The line below causes a name error since `b` isn't assigned yet.

In [22]:
# datascience
b

NameError: name 'b' is not defined

In [23]:
# polars
b

NameError: name 'b' is not defined

In [24]:
b = 3

In [25]:
b

3

**Discussion Question 1**: What will the value of `a` be once the code in the following cell has finished running?

**A.** 2 <br/>
**B.** 7 <br/>
**C.** The code will produce an error <br/>
**D.** `a` holds the value of both 2 and 7 <br/>

In [26]:
a = 2 
a + 5

7

<br/><br/><br/><br/><br/>
<br/><br/><br/><br/><br/>

In [27]:
a = a + 5
a

7

______

In [28]:
a * b

21

In [29]:
a

7

In [30]:
b

3

**Discussion Question 2**: What will the value of `total` be once the code in the following cell has finished running?

In [31]:
total = a + b
total

a = 10
total

10

______

In [32]:
total

10

In [33]:
a

10

In [34]:
total = a + b
total

13

The line below causes a *syntax error*.

In [35]:
# datascience
a + b = total

SyntaxError: cannot assign to expression here. Maybe you meant '==' instead of '='? (3885832018.py, line 2)

In [36]:
# polars
a + b = total

SyntaxError: cannot assign to expression here. Maybe you meant '==' instead of '='? (3765751495.py, line 2)

#### Why Names?

A cell with arithmetic but no names is difficult to interpret.

**Example:** On January 1, 2025, the CA Minimum Wage for Employers with 26 Employees or More increased to $16.50/hour. Calculate the yearly minimum wage of an employee who works for such an employer.

Method 1:

In [37]:
40 * 16.5

660.0

In [38]:
40 * 52 * 16.5

34320.0

Method 2:

In [39]:
ca_hourly_minimum_wage = 16.50
hours_per_week = 40
weeks_per_year = 52

In [40]:
weekly_wages = hours_per_week * ca_hourly_minimum_wage
weekly_wages

660.0

In [41]:
yearly_wages = weekly_wages * weeks_per_year
yearly_wages

34320.0

---

### Call Expressions and Arguments

Make use of functions by "calling" them with call expressions.

In [42]:
abs(-5)

5

In [43]:
abs(1 - 3)

2

Names can help us with inputs (called **arguments** in computer science jargon) to functions!

In [44]:
day_temp = 52
night_temp = 47
abs(night_temp - day_temp)

5

Functions can take multiple arguments.

In [45]:
min(14, 15)

14

<br/><br/>

Some functions can be called with a single argument *or* with multiple arguments!

In [46]:
round(123.456)

123

In [47]:
round(123.456, 1)

123.5

**STOP**

In [48]:
round(123.456, ndigits=1)

123.5

In the third line, `ndigits` is a **named argument**.

How did I know that `ndigits` would work as a name? You can use `?` to figure out everything you want to know about a function.

In [49]:
round?

In [50]:
round(number=123.456)

123

The line below causes a type error because the wrong name was used.

In [51]:
# datascience
round(123.456, digs=1)

TypeError: round() got an unexpected keyword argument 'digs'

In [52]:
# polars
round(123.456, digs=1)

TypeError: round() got an unexpected keyword argument 'digs'

## New Material: Tables

### Example: Ice cream

In [53]:
# datascience
cones = Table.read_table('cones.csv')
cones

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

In [54]:
# polars
cones_pl = pl.read_csv('cones.csv')
cones_pl

shape: (8, 3)
┌────────────┬─────────────┬───────┐
│ Flavor     ┆ Color       ┆ Price │
│ ---        ┆ ---         ┆ ---   │
│ str        ┆ str         ┆ f64   │
╞════════════╪═════════════╪═══════╡
│ strawberry ┆ pink        ┆ 3.55  │
│ chocolate  ┆ light brown ┆ 4.75  │
│ chocolate  ┆ dark brown  ┆ 5.25  │
│ strawberry ┆ pink        ┆ 5.25  │
│ chocolate  ┆ dark brown  ┆ 5.25  │
│ bubblegum  ┆ pink        ┆ 4.75  │
│ null       ┆ null        ┆ null  │
│ null       ┆ null        ┆ null  │
└────────────┴─────────────┴───────┘

In [55]:
# datascience
cones.show(3)

In [56]:
# polars
cones_pl.head(3)

shape: (3, 3)
┌────────────┬─────────────┬───────┐
│ Flavor     ┆ Color       ┆ Price │
│ ---        ┆ ---         ┆ ---   │
│ str        ┆ str         ┆ f64   │
╞════════════╪═════════════╪═══════╡
│ strawberry ┆ pink        ┆ 3.55  │
│ chocolate  ┆ light brown ┆ 4.75  │
│ chocolate  ┆ dark brown  ┆ 5.25  │
└────────────┴─────────────┴───────┘

In [57]:
# datascience
cones.show()

In [58]:
# polars
with pl.Config(tbl_rows=-1):
    display(cones_pl)

shape: (8, 3)
┌────────────┬─────────────┬───────┐
│ Flavor     ┆ Color       ┆ Price │
│ ---        ┆ ---         ┆ ---   │
│ str        ┆ str         ┆ f64   │
╞════════════╪═════════════╪═══════╡
│ strawberry ┆ pink        ┆ 3.55  │
│ chocolate  ┆ light brown ┆ 4.75  │
│ chocolate  ┆ dark brown  ┆ 5.25  │
│ strawberry ┆ pink        ┆ 5.25  │
│ chocolate  ┆ dark brown  ┆ 5.25  │
│ bubblegum  ┆ pink        ┆ 4.75  │
│ null       ┆ null        ┆ null  │
│ null       ┆ null        ┆ null  │
└────────────┴─────────────┴───────┘

#### Table Operations

In [59]:
# datascience
cones.select('Flavor')

Flavor
strawberry
chocolate
chocolate
strawberry
chocolate
bubblegum

In [60]:
# polars
cones_pl.select('Flavor')

shape: (8, 1)
┌────────────┐
│ Flavor     │
│ ---        │
│ str        │
╞════════════╡
│ strawberry │
│ chocolate  │
│ chocolate  │
│ strawberry │
│ chocolate  │
│ bubblegum  │
│ null       │
│ null       │
└────────────┘

In [61]:
# datascience
cones.select('Flavor', 'Price')

Flavor     | Price
strawberry | 3.55
chocolate  | 4.75
chocolate  | 5.25
strawberry | 5.25
chocolate  | 5.25
bubblegum  | 4.75

In [62]:
# polars
cones_pl.select('Flavor', 'Price')

shape: (8, 2)
┌────────────┬───────┐
│ Flavor     ┆ Price │
│ ---        ┆ ---   │
│ str        ┆ f64   │
╞════════════╪═══════╡
│ strawberry ┆ 3.55  │
│ chocolate  ┆ 4.75  │
│ chocolate  ┆ 5.25  │
│ strawberry ┆ 5.25  │
│ chocolate  ┆ 5.25  │
│ bubblegum  ┆ 4.75  │
│ null       ┆ null  │
│ null       ┆ null  │
└────────────┴───────┘

The line below causes an error because `Flavor` is not a name, but rather, a *column* in the `cones` table.

In [63]:
# datascience
cones.select(Flavor, 'Price')

NameError: name 'Flavor' is not defined

In [64]:
# polars
cones_pl.select(Flavor, 'Price')

NameError: name 'Flavor' is not defined

In [65]:
# datascience
cones.drop('Price')

Flavor     | Color
strawberry | pink
chocolate  | light brown
chocolate  | dark brown
strawberry | pink
chocolate  | dark brown
bubblegum  | pink

In [66]:
# polars
cones_pl.drop('Price')

shape: (8, 2)
┌────────────┬─────────────┐
│ Flavor     ┆ Color       │
│ ---        ┆ ---         │
│ str        ┆ str         │
╞════════════╪═════════════╡
│ strawberry ┆ pink        │
│ chocolate  ┆ light brown │
│ chocolate  ┆ dark brown  │
│ strawberry ┆ pink        │
│ chocolate  ┆ dark brown  │
│ bubblegum  ┆ pink        │
│ null       ┆ null        │
│ null       ┆ null        │
└────────────┴─────────────┘

In [67]:
cones

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

In [68]:
# datascience
cones_without_price = cones.drop('Price')
cones_without_price

Flavor     | Color
strawberry | pink
chocolate  | light brown
chocolate  | dark brown
strawberry | pink
chocolate  | dark brown
bubblegum  | pink

In [69]:
# polars
cones_without_price_pl = cones_pl.drop('Price')
cones_without_price_pl

shape: (8, 2)
┌────────────┬─────────────┐
│ Flavor     ┆ Color       │
│ ---        ┆ ---         │
│ str        ┆ str         │
╞════════════╪═════════════╡
│ strawberry ┆ pink        │
│ chocolate  ┆ light brown │
│ chocolate  ┆ dark brown  │
│ strawberry ┆ pink        │
│ chocolate  ┆ dark brown  │
│ bubblegum  ┆ pink        │
│ null       ┆ null        │
│ null       ┆ null        │
└────────────┴─────────────┘

In [70]:
# datascience
cones.where('Flavor', 'chocolate')

Flavor    | Color       | Price
chocolate | light brown | 4.75
chocolate | dark brown  | 5.25
chocolate | dark brown  | 5.25

In [71]:
# polars
cones_pl.filter((pl.col('Flavor') == ('chocolate')))

shape: (3, 3)
┌───────────┬─────────────┬───────┐
│ Flavor    ┆ Color       ┆ Price │
│ ---       ┆ ---         ┆ ---   │
│ str       ┆ str         ┆ f64   │
╞═══════════╪═════════════╪═══════╡
│ chocolate ┆ light brown ┆ 4.75  │
│ chocolate ┆ dark brown  ┆ 5.25  │
│ chocolate ┆ dark brown  ┆ 5.25  │
└───────────┴─────────────┴───────┘

In [72]:
# datascience
cones.sort('Price')

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
bubblegum  | pink        | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25

In [73]:
# polars
cones_pl.sort('Price')

shape: (8, 3)
┌────────────┬─────────────┬───────┐
│ Flavor     ┆ Color       ┆ Price │
│ ---        ┆ ---         ┆ ---   │
│ str        ┆ str         ┆ f64   │
╞════════════╪═════════════╪═══════╡
│ null       ┆ null        ┆ null  │
│ null       ┆ null        ┆ null  │
│ strawberry ┆ pink        ┆ 3.55  │
│ chocolate  ┆ light brown ┆ 4.75  │
│ bubblegum  ┆ pink        ┆ 4.75  │
│ chocolate  ┆ dark brown  ┆ 5.25  │
│ strawberry ┆ pink        ┆ 5.25  │
│ chocolate  ┆ dark brown  ┆ 5.25  │
└────────────┴─────────────┴───────┘

In [74]:
# datascience
cones.sort('Price', descending=True)

Flavor     | Color       | Price
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
chocolate  | light brown | 4.75
bubblegum  | pink        | 4.75
strawberry | pink        | 3.55

In [75]:
# polars
cones_pl.sort('Price', descending=True)

shape: (8, 3)
┌────────────┬─────────────┬───────┐
│ Flavor     ┆ Color       ┆ Price │
│ ---        ┆ ---         ┆ ---   │
│ str        ┆ str         ┆ f64   │
╞════════════╪═════════════╪═══════╡
│ null       ┆ null        ┆ null  │
│ null       ┆ null        ┆ null  │
│ chocolate  ┆ dark brown  ┆ 5.25  │
│ strawberry ┆ pink        ┆ 5.25  │
│ chocolate  ┆ dark brown  ┆ 5.25  │
│ chocolate  ┆ light brown ┆ 4.75  │
│ bubblegum  ┆ pink        ┆ 4.75  │
│ strawberry ┆ pink        ┆ 3.55  │
└────────────┴─────────────┴───────┘

In [76]:
# datascience
cones.sort('Flavor', descending=True)

Flavor     | Color       | Price
strawberry | pink        | 3.55
strawberry | pink        | 5.25
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

In [77]:
# polars
cones_pl.sort('Flavor', descending=True)

shape: (8, 3)
┌────────────┬─────────────┬───────┐
│ Flavor     ┆ Color       ┆ Price │
│ ---        ┆ ---         ┆ ---   │
│ str        ┆ str         ┆ f64   │
╞════════════╪═════════════╪═══════╡
│ null       ┆ null        ┆ null  │
│ null       ┆ null        ┆ null  │
│ strawberry ┆ pink        ┆ 3.55  │
│ strawberry ┆ pink        ┆ 5.25  │
│ chocolate  ┆ light brown ┆ 4.75  │
│ chocolate  ┆ dark brown  ┆ 5.25  │
│ chocolate  ┆ dark brown  ┆ 5.25  │
│ bubblegum  ┆ pink        ┆ 4.75  │
└────────────┴─────────────┴───────┘

---

### Example 2: Basketball

(for next time)

In [78]:
# datascience
# From https://github.com/erikgregorywebb/datasets/blob/master/nba-salaries.csv
nba = Table.read_table('nba_salaries.csv')
nba

rank | name             | position | team                   | salary   | season
1    | Shaquille O'Neal | C        | Los Angeles Lakers     | 17142000 | 2000
2    | Kevin Garnett    | PF       | Minnesota Timberwolves | 16806000 | 2000
3    | Alonzo Mourning  | C        | Miami Heat             | 15004000 | 2000
4    | Juwan Howard     | PF       | Washington Wizards     | 15000000 | 2000
5    | Scottie Pippen   | SF       | Portland Trail Blazers | 14795000 | 2000
6    | Karl Malone      | PF       | Utah Jazz              | 14000000 | 2000
7    | Larry Johnson    | F        | New York Knicks        | 11910000 | 2000
8    | Gary Payton      | PG       | Seattle SuperSonics    | 11020000 | 2000
9    | Rasheed Wallace  | PF       | Portland Trail Blazers | 10800000 | 2000
10   | Shawn Kemp       | C        | Cleveland Cavaliers    | 10780000 | 2000
... (9446 rows omitted)

In [79]:
# polars
# From https://github.com/erikgregorywebb/datasets/blob/master/nba-salaries.csv
nba_pl = pl.read_csv('nba_salaries.csv')
nba_pl

shape: (9_456, 6)
┌──────┬──────────────────┬──────────┬────────────────────────┬──────────┬────────┐
│ rank ┆ name             ┆ position ┆ team                   ┆ salary   ┆ season │
│ ---  ┆ ---              ┆ ---      ┆ ---                    ┆ ---      ┆ ---    │
│ i64  ┆ str              ┆ str      ┆ str                    ┆ i64      ┆ i64    │
╞══════╪══════════════════╪══════════╪════════════════════════╪══════════╪════════╡
│ 1    ┆ Shaquille O'Neal ┆ C        ┆ Los Angeles Lakers     ┆ 17142000 ┆ 2000   │
│ 2    ┆ Kevin Garnett    ┆ PF       ┆ Minnesota Timberwolves ┆ 16806000 ┆ 2000   │
│ 3    ┆ Alonzo Mourning  ┆ C        ┆ Miami Heat             ┆ 15004000 ┆ 2000   │
│ 4    ┆ Juwan Howard     ┆ PF       ┆ Washington Wizards     ┆ 15000000 ┆ 2000   │
│ 5    ┆ Scottie Pippen   ┆ SF       ┆ Portland Trail Blazers ┆ 14795000 ┆ 2000   │
│ …    ┆ …                ┆ …        ┆ …                      ┆ …        ┆ …      │
│ 524  ┆ Jimmer Fredette  ┆ G        ┆ Phoenix Suns           ┆ 208509   ┆ 2020   │
│ 525  ┆ Jontay Porter    ┆ PF       ┆ Memphis Grizzlies      ┆ 197933   ┆ 2020   │
│ 526  ┆ Anthony Tolliver ┆ PF       ┆ Memphis Grizzlies      ┆ 183115   ┆ 2020   │
│ 527  ┆ Tyler Johnson    ┆ SG       ┆ Phoenix Suns           ┆ 183115   ┆ 2020   │
│ 528  ┆ Luguentz Dort    ┆ SG       ┆ Oklahoma City Thunder  ┆ 155647   ┆ 2020   │
└──────┴──────────────────┴──────────┴────────────────────────┴──────────┴────────┘

In [80]:
# datascience
point_guards = nba.where('position', 'PG').where('season', 2020)

In [81]:
# polars
point_guards_pl = nba_pl.filter((pl.col('position') == ('PG'))).filter((pl.col('season') == (2020)))

In [82]:
point_guards

rank | name              | position | team                   | salary   | season
1    | Stephen Curry     | PG       | Golden State Warriors  | 40231758 | 2020
2    | Chris Paul        | PG       | Oklahoma City Thunder  | 38506482 | 2020
3    | Russell Westbrook | PG       | Houston Rockets        | 38506482 | 2020
4    | John Wall         | PG       | Washington Wizards     | 38199000 | 2020
8    | Kyle Lowry        | PG       | Toronto Raptors        | 34996296 | 2020
14   | Kemba Walker      | PG       | Boston Celtics         | 32742000 | 2020
16   | Mike Conley       | PG       | Utah Jazz              | 32511624 | 2020
17   | Kyrie Irving      | PG       | Brooklyn Nets          | 31742000 | 2020
21   | Damian Lillard    | PG       | Portland Trail Blazers | 29802321 | 2020
52   | Malcolm Brogdon   | PG       | Indiana Pacers         | 20000000 | 2020
... (72 rows omitted)

In [83]:
# datascience
point_guards.drop('position')

rank | name              | team                   | salary   | season
1    | Stephen Curry     | Golden State Warriors  | 40231758 | 2020
2    | Chris Paul        | Oklahoma City Thunder  | 38506482 | 2020
3    | Russell Westbrook | Houston Rockets        | 38506482 | 2020
4    | John Wall         | Washington Wizards     | 38199000 | 2020
8    | Kyle Lowry        | Toronto Raptors        | 34996296 | 2020
14   | Kemba Walker      | Boston Celtics         | 32742000 | 2020
16   | Mike Conley       | Utah Jazz              | 32511624 | 2020
17   | Kyrie Irving      | Brooklyn Nets          | 31742000 | 2020
21   | Damian Lillard    | Portland Trail Blazers | 29802321 | 2020
52   | Malcolm Brogdon   | Indiana Pacers         | 20000000 | 2020
... (72 rows omitted)

In [84]:
# polars
point_guards_pl.drop('position')

shape: (82, 5)
┌──────┬───────────────────┬───────────────────────┬──────────┬────────┐
│ rank ┆ name              ┆ team                  ┆ salary   ┆ season │
│ ---  ┆ ---               ┆ ---                   ┆ ---      ┆ ---    │
│ i64  ┆ str               ┆ str                   ┆ i64      ┆ i64    │
╞══════╪═══════════════════╪═══════════════════════╪══════════╪════════╡
│ 1    ┆ Stephen Curry     ┆ Golden State Warriors ┆ 40231758 ┆ 2020   │
│ 2    ┆ Chris Paul        ┆ Oklahoma City Thunder ┆ 38506482 ┆ 2020   │
│ 3    ┆ Russell Westbrook ┆ Houston Rockets       ┆ 38506482 ┆ 2020   │
│ 4    ┆ John Wall         ┆ Washington Wizards    ┆ 38199000 ┆ 2020   │
│ 8    ┆ Kyle Lowry        ┆ Toronto Raptors       ┆ 34996296 ┆ 2020   │
│ …    ┆ …                 ┆ …                     ┆ …        ┆ …      │
│ 490  ┆ Jalen Lecque      ┆ Phoenix Suns          ┆ 898310   ┆ 2020   │
│ 510  ┆ Chris Clemons     ┆ Houston Rockets       ┆ 563347   ┆ 2020   │
│ 512  ┆ Brandon Goodwin   ┆ Atlanta Hawks         ┆ 522738   ┆ 2020   │
│ 513  ┆ Reggie Jackson    ┆ LA Clippers           ┆ 512721   ┆ 2020   │
│ 522  ┆ Ky Bowman         ┆ Golden State Warriors ┆ 350189   ┆ 2020   │
└──────┴───────────────────┴───────────────────────┴──────────┴────────┘

In [85]:
point_guards

rank | name              | position | team                   | salary   | season
1    | Stephen Curry     | PG       | Golden State Warriors  | 40231758 | 2020
2    | Chris Paul        | PG       | Oklahoma City Thunder  | 38506482 | 2020
3    | Russell Westbrook | PG       | Houston Rockets        | 38506482 | 2020
4    | John Wall         | PG       | Washington Wizards     | 38199000 | 2020
8    | Kyle Lowry        | PG       | Toronto Raptors        | 34996296 | 2020
14   | Kemba Walker      | PG       | Boston Celtics         | 32742000 | 2020
16   | Mike Conley       | PG       | Utah Jazz              | 32511624 | 2020
17   | Kyrie Irving      | PG       | Brooklyn Nets          | 31742000 | 2020
21   | Damian Lillard    | PG       | Portland Trail Blazers | 29802321 | 2020
52   | Malcolm Brogdon   | PG       | Indiana Pacers         | 20000000 | 2020
... (72 rows omitted)

In [86]:
# datascience
point_guards = point_guards.drop('rank', 'position', 'season')

In [87]:
# polars
point_guards_pl = point_guards_pl.drop('rank', 'position', 'season')

In [88]:
# datascience
point_guards.show(10)

In [89]:
# polars
point_guards_pl.head(10)

shape: (10, 3)
┌───────────────────┬────────────────────────┬──────────┐
│ name              ┆ team                   ┆ salary   │
│ ---               ┆ ---                    ┆ ---      │
│ str               ┆ str                    ┆ i64      │
╞═══════════════════╪════════════════════════╪══════════╡
│ Stephen Curry     ┆ Golden State Warriors  ┆ 40231758 │
│ Chris Paul        ┆ Oklahoma City Thunder  ┆ 38506482 │
│ Russell Westbrook ┆ Houston Rockets        ┆ 38506482 │
│ John Wall         ┆ Washington Wizards     ┆ 38199000 │
│ Kyle Lowry        ┆ Toronto Raptors        ┆ 34996296 │
│ Kemba Walker      ┆ Boston Celtics         ┆ 32742000 │
│ Mike Conley       ┆ Utah Jazz              ┆ 32511624 │
│ Kyrie Irving      ┆ Brooklyn Nets          ┆ 31742000 │
│ Damian Lillard    ┆ Portland Trail Blazers ┆ 29802321 │
│ Malcolm Brogdon   ┆ Indiana Pacers         ┆ 20000000 │
└───────────────────┴────────────────────────┴──────────┘

In [90]:
# datascience
point_guards.sort('salary').show(10)

In [91]:
# polars
point_guards_pl.sort('salary').head(10)

shape: (10, 3)
┌─────────────────┬───────────────────────┬─────────┐
│ name            ┆ team                  ┆ salary  │
│ ---             ┆ ---                   ┆ ---     │
│ str             ┆ str                   ┆ i64     │
╞═════════════════╪═══════════════════════╪═════════╡
│ Ky Bowman       ┆ Golden State Warriors ┆ 350189  │
│ Reggie Jackson  ┆ LA Clippers           ┆ 512721  │
│ Brandon Goodwin ┆ Atlanta Hawks         ┆ 522738  │
│ Chris Clemons   ┆ Houston Rockets       ┆ 563347  │
│ Justin Robinson ┆ Washington Wizards    ┆ 898310  │
│ Jalen Lecque    ┆ Phoenix Suns          ┆ 898310  │
│ Gary Payton II  ┆ Washington Wizards    ┆ 1052909 │
│ Carsen Edwards  ┆ Boston Celtics        ┆ 1228026 │
│ Devonte' Graham ┆ Charlotte Hornets     ┆ 1416852 │
│ Jevon Carter    ┆ Phoenix Suns          ┆ 1416852 │
└─────────────────┴───────────────────────┴─────────┘

In [92]:
# datascience
point_guards.sort('salary', descending=True).show(10)

In [93]:
# polars
point_guards_pl.sort('salary', descending=True).head(10)

shape: (10, 3)
┌───────────────────┬────────────────────────┬──────────┐
│ name              ┆ team                   ┆ salary   │
│ ---               ┆ ---                    ┆ ---      │
│ str               ┆ str                    ┆ i64      │
╞═══════════════════╪════════════════════════╪══════════╡
│ Stephen Curry     ┆ Golden State Warriors  ┆ 40231758 │
│ Chris Paul        ┆ Oklahoma City Thunder  ┆ 38506482 │
│ Russell Westbrook ┆ Houston Rockets        ┆ 38506482 │
│ John Wall         ┆ Washington Wizards     ┆ 38199000 │
│ Kyle Lowry        ┆ Toronto Raptors        ┆ 34996296 │
│ Kemba Walker      ┆ Boston Celtics         ┆ 32742000 │
│ Mike Conley       ┆ Utah Jazz              ┆ 32511624 │
│ Kyrie Irving      ┆ Brooklyn Nets          ┆ 31742000 │
│ Damian Lillard    ┆ Portland Trail Blazers ┆ 29802321 │
│ Malcolm Brogdon   ┆ Indiana Pacers         ┆ 20000000 │
└───────────────────┴────────────────────────┴──────────┘

The order of the computations does matter!

**Discussion Question**: Which one of the following two lines of code fail?

In [94]:
# datascience
nba.drop('position').where('position', 'PG')

ValueError: label "position" not in labels ('rank', 'name', 'team', 'salary', 'season')

In [95]:
# polars
nba_pl.drop('position').filter((pl.col('position') == ('PG')))

ColumnNotFoundError: unable to find column "position"; valid columns: ["rank", "name", "team", "salary", "season"]

In [96]:
# datascience
nba.where('position', 'PG').drop('position')

rank | name             | team                   | salary   | season
8    | Gary Payton      | Seattle SuperSonics    | 11020000 | 2000
11   | Damon Stoudamire | Portland Trail Blazers | 10125000 | 2000
20   | Stephon Marbury  | New Jersey Nets        | 9000000  | 2000
24   | Nick Van Exel    | Denver Nuggets         | 8354000  | 2000
26   | Terrell Brandon  | Minnesota Timberwolves | 7400000  | 2000
34   | Jason Kidd       | Phoenix Suns           | 6858000  | 2000
35   | Kenny Anderson   | Boston Celtics         | 6680000  | 2000
39   | Steve Nash       | Dallas Mavericks       | 5500000  | 2000
55   | Charlie Ward     | New York Knicks        | 4540000  | 2000
61   | Darrel Armstrong | Orlando Magic          | 4125000  | 2000
... (1465 rows omitted)

In [97]:
# polars
nba_pl.filter((pl.col('position') == ('PG'))).drop('position')

shape: (1_475, 5)
┌──────┬──────────────────┬────────────────────────┬──────────┬────────┐
│ rank ┆ name             ┆ team                   ┆ salary   ┆ season │
│ ---  ┆ ---              ┆ ---                    ┆ ---      ┆ ---    │
│ i64  ┆ str              ┆ str                    ┆ i64      ┆ i64    │
╞══════╪══════════════════╪════════════════════════╪══════════╪════════╡
│ 8    ┆ Gary Payton      ┆ Seattle SuperSonics    ┆ 11020000 ┆ 2000   │
│ 11   ┆ Damon Stoudamire ┆ Portland Trail Blazers ┆ 10125000 ┆ 2000   │
│ 20   ┆ Stephon Marbury  ┆ New Jersey Nets        ┆ 9000000  ┆ 2000   │
│ 24   ┆ Nick Van Exel    ┆ Denver Nuggets         ┆ 8354000  ┆ 2000   │
│ 26   ┆ Terrell Brandon  ┆ Minnesota Timberwolves ┆ 7400000  ┆ 2000   │
│ …    ┆ …                ┆ …                      ┆ …        ┆ …      │
│ 490  ┆ Jalen Lecque     ┆ Phoenix Suns           ┆ 898310   ┆ 2020   │
│ 510  ┆ Chris Clemons    ┆ Houston Rockets        ┆ 563347   ┆ 2020   │
│ 512  ┆ Brandon Goodwin  ┆ Atlanta Hawks          ┆ 522738   ┆ 2020   │
│ 513  ┆ Reggie Jackson   ┆ LA Clippers            ┆ 512721   ┆ 2020   │
│ 522  ┆ Ky Bowman        ┆ Golden State Warriors  ┆ 350189   ┆ 2020   │
└──────┴──────────────────┴────────────────────────┴──────────┴────────┘