# Pivots and Joins

In [1]:
# datascience
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')
import warnings
warnings.simplefilter(action='ignore',category=np.exceptions.VisibleDeprecationWarning)

In [2]:
# polars
import polars as pl
from IPython.display import display

## Rows from lists

In [3]:
# datascience
Table().with_columns('Numbers', [1, 2, 3])

Numbers
1
2
3

In [4]:
# polars
pl.DataFrame([
    pl.Series('Numbers', [1, 2, 3])
])

shape: (3, 1)
┌─────────┐
│ Numbers │
│ ---     │
│ i64     │
╞═════════╡
│ 1       │
│ 2       │
│ 3       │
└─────────┘

In [5]:
# datascience
drinks = Table(['Drink', 'Cafe', 'Price'])
drinks

Drink | Cafe | Price

In [6]:
# polars
drinks_pl = pl.DataFrame(schema={c: pl.Utf8 for c in ['Drink', 'Cafe', 'Price']})
drinks_pl

shape: (0, 3)
┌───────┬──────┬───────┐
│ Drink ┆ Cafe ┆ Price │
│ ---   ┆ ---  ┆ ---   │
│ str   ┆ str  ┆ str   │
╞═══════╪══════╪═══════╡
└───────┴──────┴───────┘

In [7]:
# datascience
drinks = drinks.with_rows([
    ['Milk Tea', 'Asha', 5.5],
    ['Espresso', 'Strada',  1.75],
    ['Latte',    'Strada',  3.25],
    ['Espresso', "FSM",   2]
])
drinks

Drink    | Cafe   | Price
Milk Tea | Asha   | 5.5
Espresso | Strada | 1.75
Latte    | Strada | 3.25
Espresso | FSM    | 2

In [8]:
# polars
drinks_pl = pl.DataFrame([
    ['Milk Tea', 'Asha', 5.5],
    ['Espresso', 'Strada',  1.75],
    ['Latte',    'Strada',  3.25],
    ['Espresso', "FSM",   2]
], schema=drinks_pl.columns, orient='row')
drinks_pl

shape: (4, 3)
┌──────────┬────────┬───────┐
│ Drink    ┆ Cafe   ┆ Price │
│ ---      ┆ ---    ┆ ---   │
│ str      ┆ str    ┆ f64   │
╞══════════╪════════╪═══════╡
│ Milk Tea ┆ Asha   ┆ 5.5   │
│ Espresso ┆ Strada ┆ 1.75  │
│ Latte    ┆ Strada ┆ 3.25  │
│ Espresso ┆ FSM    ┆ 2.0   │
└──────────┴────────┴───────┘

## Cross-classification: grouping by two columns

Do right-handed people tend to sleep on their left side and left-handed people sleep on their right?

In [9]:
# datascience
survey = Table.read_table('welcome_survey_fa26.csv')
survey.show(3)

In [10]:
# polars
survey_pl = pl.read_csv('welcome_survey_fa26.csv')
survey_pl.head(3)

shape: (3, 6)
┌──────────────┬─────────────────┬─────────────┬──────────────┬────────────────────┬───────────┐
│ Extroversion ┆ Text Recipients ┆ Sleep Hours ┆ Handedness   ┆ Sleep Position     ┆ Piercings │
│ ---          ┆ ---             ┆ ---         ┆ ---          ┆ ---                ┆ ---       │
│ i64          ┆ i64             ┆ f64         ┆ str          ┆ str                ┆ i64       │
╞══════════════╪═════════════════╪═════════════╪══════════════╪════════════════════╪═══════════╡
│ 7            ┆ 5               ┆ 6.0         ┆ Right-handed ┆ On your right side ┆ 0         │
│ 7            ┆ 10              ┆ 7.0         ┆ Ambidextrous ┆ On your right side ┆ 2         │
│ 3            ┆ 7               ┆ 9.0         ┆ Left-handed  ┆ On your left side  ┆ 0         │
└──────────────┴─────────────────┴─────────────┴──────────────┴────────────────────┴───────────┘

In [11]:
# datascience
survey.group(['Handedness', 'Sleep Position']).show()

In [12]:
# polars
with pl.Config(tbl_rows=-1):
    display(survey_pl.group_by(['Handedness', 'Sleep Position']).len(name='count').sort(['Handedness', 'Sleep Position']))

shape: (12, 3)
┌─────────────────────────────────┬────────────────────┬───────┐
│ Handedness                      ┆ Sleep Position     ┆ count │
│ ---                             ┆ ---                ┆ ---   │
│ str                             ┆ str                ┆ u32   │
╞═════════════════════════════════╪════════════════════╪═══════╡
│ Ambidextrous                    ┆ On your back       ┆ 3     │
│ Ambidextrous                    ┆ On your left side  ┆ 1     │
│ Ambidextrous                    ┆ On your right side ┆ 5     │
│ I can write with both hands an… ┆ On your back       ┆ 1     │
│ Left-handed                     ┆ On your back       ┆ 20    │
│ Left-handed                     ┆ On your left side  ┆ 33    │
│ Left-handed                     ┆ On your right side ┆ 29    │
│ Left-handed                     ┆ On your stomach    ┆ 13    │
│ Right-handed                    ┆ On your back       ┆ 309   │
│ Right-handed                    ┆ On your left side  ┆ 267   │
│ Right-handed                    ┆ On your right side ┆ 334   │
│ Right-handed                    ┆ On your stomach    ┆ 107   │
└─────────────────────────────────┴────────────────────┴───────┘

In [13]:
# datascience
survey.group(['Handedness', 'Sleep Position'], np.average).show()

In [14]:
# polars
with pl.Config(tbl_rows=-1):
    display((lambda _df: _df.group_by(['Handedness', 'Sleep Position']).agg([getattr(pl.col(c), 'mean')().alias(f'{c} average') for c, t in _df.schema.items() if c not in (['Handedness', 'Sleep Position'] if isinstance(['Handedness', 'Sleep Position'], list) else [['Handedness', 'Sleep Position']]) and (t.is_numeric())]).sort(['Handedness', 'Sleep Position']))(survey_pl))

shape: (12, 6)
┌──────────────────┬────────────────────┬──────────────┬────────────┬─────────────┬───────────┐
│ Handedness       ┆ Sleep Position     ┆ Extroversion ┆ Text       ┆ Sleep Hours ┆ Piercings │
│ ---              ┆ ---                ┆ average      ┆ Recipients ┆ average     ┆ average   │
│ str              ┆ str                ┆ ---          ┆ average    ┆ ---         ┆ ---       │
│                  ┆                    ┆ f64          ┆ ---        ┆ f64         ┆ f64       │
│                  ┆                    ┆              ┆ f64        ┆             ┆           │
╞══════════════════╪════════════════════╪══════════════╪════════════╪═════════════╪═══════════╡
│ Ambidextrous     ┆ On your back       ┆ 6.666667     ┆ 10.666667  ┆ 7.333333    ┆ 0.0       │
│ Ambidextrous     ┆ On your left side  ┆ 3.0          ┆ 1.0        ┆ 6.0         ┆ 2.0       │
│ Ambidextrous     ┆ On your right side ┆ 5.4          ┆ 4.8        ┆ 6.7         ┆ 1.0       │
│ I can write with ┆ On your back       ┆ 1.0          ┆ 12.0       ┆ 8.0         ┆ 0.0       │
│ both hands an…   ┆                    ┆              ┆            ┆             ┆           │
│ Left-handed      ┆ On your back       ┆ 5.45         ┆ 10.6       ┆ 6.75        ┆ 0.7       │
│ Left-handed      ┆ On your left side  ┆ 6.060606     ┆ 7.787879   ┆ 7.060606    ┆ 0.878788  │
│ Left-handed      ┆ On your right side ┆ 6.103448     ┆ 7.448276   ┆ 7.189655    ┆ 1.482759  │
│ Left-handed      ┆ On your stomach    ┆ 5.384615     ┆ 8.769231   ┆ 7.384615    ┆ 2.307692  │
│ Right-handed     ┆ On your back       ┆ 5.721683     ┆ 6.608414   ┆ 7.113269    ┆ 0.977346  │
│ Right-handed     ┆ On your left side  ┆ 5.58427      ┆ 6.876404   ┆ 6.899625    ┆ 1.681648  │
│ Right-handed     ┆ On your right side ┆ 5.874251     ┆ 6.769461   ┆ 7.076347    ┆ 1.586826  │
│ Right-handed     ┆ On your stomach    ┆ 5.897196     ┆ 7.859813   ┆ 7.060748    ┆ 1.439252  │
└──────────────────┴────────────────────┴──────────────┴────────────┴─────────────┴───────────┘

## Pivot Tables

In [15]:
# datascience
survey.group('Handedness')

Handedness                           | count
Ambidextrous                         | 9
I can write with both hands and feet | 1
Left-handed                          | 95
Right-handed                         | 1017

In [16]:
# polars
survey_pl.group_by('Handedness').len(name='count').sort('Handedness')

shape: (4, 2)
┌─────────────────────────────────┬───────┐
│ Handedness                      ┆ count │
│ ---                             ┆ ---   │
│ str                             ┆ u32   │
╞═════════════════════════════════╪═══════╡
│ Ambidextrous                    ┆ 9     │
│ I can write with both hands an… ┆ 1     │
│ Left-handed                     ┆ 95    │
│ Right-handed                    ┆ 1017  │
└─────────────────────────────────┴───────┘

In [17]:
# datascience
survey.pivot('Sleep Position', 'Handedness')

Handedness                           | On your back | On your left side | On your right side | On your stomach
Ambidextrous                         | 3            | 1                 | 5                  | 0
I can write with both hands and feet | 1            | 0                 | 0                  | 0
Left-handed                          | 20           | 33                | 29                 | 13
Right-handed                         | 309          | 267               | 334                | 107

In [18]:
# polars
survey_pl.pivot('Sleep Position', index='Handedness', aggregate_function='len').sort('Handedness')

shape: (4, 17)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Handednes ┆ Extrovers ┆ Extrovers ┆ Extrovers ┆ … ┆ Piercings ┆ Piercings ┆ Piercings ┆ Piercing │
│ s         ┆ ion_On    ┆ ion_On    ┆ ion_On    ┆   ┆ _On your  ┆ _On your  ┆ _On your  ┆ s_On     │
│ ---       ┆ your      ┆ your left ┆ your back ┆   ┆ right     ┆ left side ┆ back      ┆ your     │
│ str       ┆ right     ┆ side      ┆ ---       ┆   ┆ side      ┆ ---       ┆ ---       ┆ stomach  │
│           ┆ sid…      ┆ ---       ┆ u32       ┆   ┆ ---       ┆ u32       ┆ u32       ┆ ---      │
│           ┆ ---       ┆ u32       ┆           ┆   ┆ u32       ┆           ┆           ┆ u32      │
│           ┆ u32       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Ambidextr ┆ 5         ┆ 1         ┆ 3         ┆ … ┆ 5         ┆ 1         ┆ 3         ┆ 0        │
│ ous       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ I can     ┆ 0         ┆ 0         ┆ 1         ┆ … ┆ 0         ┆ 0         ┆ 1         ┆ 0        │
│ write     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ with both ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ hands an… ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Left-hand ┆ 29        ┆ 33        ┆ 20        ┆ … ┆ 29        ┆ 33        ┆ 20        ┆ 13       │
│ ed        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Right-han ┆ 334       ┆ 267       ┆ 309       ┆ … ┆ 334       ┆ 267       ┆ 309       ┆ 107      │
│ ded       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

**DISCUSS**: Why do the group and pivot tables have different numbers of entries?

In [19]:
# datascience
survey.pivot('Sleep Position', 
             'Handedness', 
             values='Sleep Hours', 
             collect=np.average)

Handedness                           | On your back | On your left side | On your right side | On your stomach
Ambidextrous                         | 7.33333      | 6                 | 6.7                | 0
I can write with both hands and feet | 8            | 0                 | 0                  | 0
Left-handed                          | 6.75         | 7.06061           | 7.18966            | 7.38462
Right-handed                         | 7.11327      | 6.89963           | 7.07635            | 7.06075

In [20]:
# polars
survey_pl.pivot('Sleep Position', index='Handedness', values='Sleep Hours', aggregate_function='mean').sort('Handedness')

shape: (4, 5)
┌────────────────────────┬────────────────────┬───────────────────┬──────────────┬─────────────────┐
│ Handedness             ┆ On your right side ┆ On your left side ┆ On your back ┆ On your stomach │
│ ---                    ┆ ---                ┆ ---               ┆ ---          ┆ ---             │
│ str                    ┆ f64                ┆ f64               ┆ f64          ┆ f64             │
╞════════════════════════╪════════════════════╪═══════════════════╪══════════════╪═════════════════╡
│ Ambidextrous           ┆ 6.7                ┆ 6.0               ┆ 7.333333     ┆ null            │
│ I can write with both  ┆ null               ┆ null              ┆ 8.0          ┆ null            │
│ hands an…              ┆                    ┆                   ┆              ┆                 │
│ Left-handed            ┆ 7.189655           ┆ 7.060606          ┆ 6.75         ┆ 7.384615        │
│ Right-handed           ┆ 7.076347           ┆ 6.899625          ┆ 7.113269     ┆ 7.060748        │
└────────────────────────┴────────────────────┴───────────────────┴──────────────┴─────────────────┘

**DISCUSS**: In the above pivot table, what does one number mean?

## Discussion Questions ##

In [21]:
# datascience
# From the CORGIS Dataset Project
# By Austin Cory Bart acbart@vt.edu
# Version 2.0.0, created 3/22/2016
# https://corgis-edu.github.io/corgis/csv/skyscrapers/

sky = Table.read_table('skyscrapers.csv')
sky = (sky.with_column('age', 2022 - sky.column('completed'))
          .drop('completed'))
sky.show(3)

In [22]:
# polars
# From the CORGIS Dataset Project
# By Austin Cory Bart acbart@vt.edu
# Version 2.0.0, created 3/22/2016
# https://corgis-edu.github.io/corgis/csv/skyscrapers/

sky_pl = pl.read_csv('skyscrapers.csv')
sky_pl = (sky_pl.with_columns((2022 - sky_pl.get_column('completed')).alias('age'))
          .drop('completed'))
sky_pl.head(3)

shape: (3, 5)
┌────────────────────────┬─────────────────┬───────────────┬────────────┬─────┐
│ name                   ┆ material        ┆ city          ┆ height     ┆ age │
│ ---                    ┆ ---             ┆ ---           ┆ ---        ┆ --- │
│ str                    ┆ str             ┆ str           ┆ f64        ┆ i64 │
╞════════════════════════╪═════════════════╪═══════════════╪════════════╪═════╡
│ One World Trade Center ┆ mixed/composite ┆ New York City ┆ 541.299988 ┆ 8   │
│ Willis Tower           ┆ steel           ┆ Chicago       ┆ 442.140015 ┆ 48  │
│ 432 Park Avenue        ┆ concrete        ┆ New York City ┆ 425.5      ┆ 7   │
└────────────────────────┴─────────────────┴───────────────┴────────────┴─────┘

### 1. For each city, what’s the height of the tallest building for each material?

In [23]:
# YOUR CODE HERE

### 2. For each city, what’s the height difference between the tallest steel building and the tallest concrete building?

In [24]:
# YOUR CODE HERE

---

#### **WARNING: ANSWERS BELOW**

In [25]:
# datascience
sky.select('material', 'city', 'height').group(['city', 'material'], collect=max)

city      | material        | height max
Atlanta   | concrete        | 264.25
Atlanta   | mixed/composite | 311.8
Atlanta   | steel           | 169.47
Austin    | concrete        | 208.15
Austin    | steel           | 93.6
Baltimore | concrete        | 161.24
Baltimore | steel           | 155.15
Boston    | concrete        | 121.92
Boston    | mixed/composite | 139
Boston    | steel           | 240.79
... (81 rows omitted)

In [26]:
# polars
(lambda _df: _df.group_by(['city', 'material']).agg([pl.col(c).max().alias(f'{c} max') for c, t in _df.schema.items() if c not in (['city', 'material'] if isinstance(['city', 'material'], list) else [['city', 'material']]) and (True)]).sort(['city', 'material']))(sky_pl.select('material', 'city', 'height'))

shape: (91, 3)
┌───────────────────┬─────────────────┬────────────┐
│ city              ┆ material        ┆ height max │
│ ---               ┆ ---             ┆ ---        │
│ str               ┆ str             ┆ f64        │
╞═══════════════════╪═════════════════╪════════════╡
│ Atlanta           ┆ concrete        ┆ 264.25     │
│ Atlanta           ┆ mixed/composite ┆ 311.799988 │
│ Atlanta           ┆ steel           ┆ 169.470001 │
│ Austin            ┆ concrete        ┆ 208.149994 │
│ Austin            ┆ steel           ┆ 93.599998  │
│ …                 ┆ …               ┆ …          │
│ Seattle           ┆ steel           ┆ 235.309998 │
│ St. Louis         ┆ concrete        ┆ 100.660004 │
│ St. Louis         ┆ mixed/composite ┆ 180.75     │
│ St. Louis         ┆ steel           ┆ 147.600006 │
│ Sunny Isles Beach ┆ concrete        ┆ 196.0      │
└───────────────────┴─────────────────┴────────────┘

In [27]:
# datascience
tallest = sky.pivot('material', 'city', values='height', collect=max)
tallest.show()

In [28]:
# polars
tallest_pl = sky_pl.pivot('material', index='city', values='height', aggregate_function='max').sort('city')
with pl.Config(tbl_rows=-1):
    display(tallest_pl)

shape: (35, 4)
┌───────────────────┬─────────────────┬────────────┬────────────┐
│ city              ┆ mixed/composite ┆ steel      ┆ concrete   │
│ ---               ┆ ---             ┆ ---        ┆ ---        │
│ str               ┆ f64             ┆ f64        ┆ f64        │
╞═══════════════════╪═════════════════╪════════════╪════════════╡
│ Atlanta           ┆ 311.799988      ┆ 169.470001 ┆ 264.25     │
│ Austin            ┆ null            ┆ 93.599998  ┆ 208.149994 │
│ Baltimore         ┆ null            ┆ 155.149994 ┆ 161.240005 │
│ Boston            ┆ 139.0           ┆ 240.789993 ┆ 121.919998 │
│ Charlotte         ┆ 239.699997      ┆ 179.229996 ┆ 265.480011 │
│ Chicago           ┆ 306.940002      ┆ 442.140015 ┆ 423.220001 │
│ Cincinnati        ┆ 202.690002      ┆ 175.0      ┆ 125.0      │
│ Cleveland         ┆ 288.649994      ┆ 215.800003 ┆ 125.0      │
│ Columbus          ┆ null            ┆ 169.300003 ┆ 79.25      │
│ Dallas            ┆ 280.720001      ┆ 270.059998 ┆ 176.479996 │
│ Denver            ┆ 212.75          ┆ 217.630005 ┆ 194.75     │
│ Detroit           ┆ null            ┆ 173.259995 ┆ 221.490005 │
│ Honolulu          ┆ null            ┆ 130.75     ┆ 129.800003 │
│ Houston           ┆ 305.410004      ┆ 302.369995 ┆ 217.630005 │
│ Indianapolis      ┆ null            ┆ 213.669998 ┆ 128.169998 │
│ Jersey City       ┆ null            ┆ 238.050003 ┆ 162.160004 │
│ Kansas City       ┆ null            ┆ 146.610001 ┆ 189.889999 │
│ Las Vegas         ┆ 195.679993      ┆ 164.600006 ┆ 350.220001 │
│ Los Angeles       ┆ 118.260002      ┆ 310.290009 ┆ 145.699997 │
│ Miami             ┆ 232.800003      ┆ 147.520004 ┆ 240.410004 │
│ Miami Beach       ┆ null            ┆ null       ┆ 170.389999 │
│ Milwaukee         ┆ null            ┆ 183.190002 ┆ 136.0      │
│ Minneapolis       ┆ 241.380005      ┆ 144.639999 ┆ 203.580002 │
│ New York City     ┆ 541.299988      ┆ 381.0      ┆ 425.5      │
│ Philadelphia      ┆ 296.730011      ┆ 288.040009 ┆ 157.889999 │
│ Phoenix           ┆ 114.0           ┆ 147.220001 ┆ 124.099998 │
│ Pittsburgh        ┆ 172.0           ┆ 256.339996 ┆ 89.300003  │
│ Portland          ┆ 127.400002      ┆ 166.419998 ┆ 155.149994 │
│ Sacramento        ┆ 115.82          ┆ 122.599998 ┆ 106.980003 │
│ Salt Lake City    ┆ null            ┆ 128.630005 ┆ 114.910004 │
│ San Diego         ┆ 144.779999      ┆ 152.399994 ┆ 151.490005 │
│ San Francisco     ┆ 260.0           ┆ 237.440002 ┆ 196.600006 │
│ Seattle           ┆ 284.380005      ┆ 235.309998 ┆ 138.690002 │
│ St. Louis         ┆ 180.75          ┆ 147.600006 ┆ 100.660004 │
│ Sunny Isles Beach ┆ null            ┆ null       ┆ 196.0      │
└───────────────────┴─────────────────┴────────────┴────────────┘

In [29]:
# datascience
diffs = Table().with_columns(
    'city', tallest.column('city'),
    'difference', abs(tallest.column('steel') - tallest.column('concrete'))
)
diffs

city       | difference
Atlanta    | 94.78
Austin     | 114.55
Baltimore  | 6.09001
Boston     | 118.87
Charlotte  | 86.25
Chicago    | 18.92
Cincinnati | 50
Cleveland  | 90.8
Columbus   | 90.05
Dallas     | 93.58
... (25 rows omitted)

In [30]:
# polars
diffs_pl = pl.DataFrame([
    (tallest_pl.get_column('city')).alias('city'),
    (abs(tallest_pl.get_column('steel') - tallest_pl.get_column('concrete'))).alias('difference')
])
diffs_pl

shape: (35, 2)
┌───────────────────┬────────────┐
│ city              ┆ difference │
│ ---               ┆ ---        │
│ str               ┆ f64        │
╞═══════════════════╪════════════╡
│ Atlanta           ┆ 94.779999  │
│ Austin            ┆ 114.549995 │
│ Baltimore         ┆ 6.090012   │
│ Boston            ┆ 118.869995 │
│ Charlotte         ┆ 86.250015  │
│ …                 ┆ …          │
│ San Diego         ┆ 0.909988   │
│ San Francisco     ┆ 40.839996  │
│ Seattle           ┆ 96.619995  │
│ St. Louis         ┆ 46.940002  │
│ Sunny Isles Beach ┆ null       │
└───────────────────┴────────────┘

In [31]:
# datascience
diffs.sort('difference', descending=True)

city              | difference
Sunny Isles Beach | 196
Las Vegas         | 185.62
Miami Beach       | 170.39
Pittsburgh        | 167.04
Los Angeles       | 164.59
Philadelphia      | 130.15
Boston            | 118.87
Austin            | 114.55
Seattle           | 96.62
Atlanta           | 94.78
... (25 rows omitted)

In [32]:
# polars
diffs_pl.sort('difference', descending=True)

shape: (35, 2)
┌───────────────────┬────────────┐
│ city              ┆ difference │
│ ---               ┆ ---        │
│ str               ┆ f64        │
╞═══════════════════╪════════════╡
│ Miami Beach       ┆ null       │
│ Sunny Isles Beach ┆ null       │
│ Las Vegas         ┆ 185.619995 │
│ Pittsburgh        ┆ 167.039993 │
│ Los Angeles       ┆ 164.590012 │
│ …                 ┆ …          │
│ Salt Lake City    ┆ 13.720001  │
│ Portland          ┆ 11.270004  │
│ Baltimore         ┆ 6.090012   │
│ Honolulu          ┆ 0.949997   │
│ San Diego         ┆ 0.909988   │
└───────────────────┴────────────┘

### 3. Generate a table of the names of the oldest buildings for each material for each city.

In [33]:
# datascience
# Hint: You can use sort to find the name of the oldest building in the dataset
sky.sort('age', descending=True).column('name').item(0)

# YOUR CODE HERE

'Statue of Liberty'

In [34]:
# polars
# Hint: You can use sort to find the name of the oldest building in the dataset
sky_pl.sort('age', descending=True).get_column('name').item(0)

# YOUR CODE HERE

'Statue of Liberty'

---

#### **WARNING: ANSWERS BELOW**

In [35]:
# datascience
def first(s):
    "Return the first element in an array."
    return s.item(0)

(sky
 .sort('age', descending=True)
 .pivot('material', 'city', 'name', first)
)#.where('city', 'San Francisco')

city       | concrete                         | mixed/composite                           | steel
Atlanta    | Westin Peachtree Plaza           | One Atlantic Center                       | FlatironCity
Austin     | One American Center              |                                           | University of Texas Tower
Baltimore  | Charles Towers North Apartments  |                                           | Emerson Tower
Boston     | Harbor Towers I                  | Ellison Building                          | Marriott's Custom House
Charlotte  | Bank of America Corporate Center | Hearst Tower                              | Midtown Plaza
Chicago    | The Powhatan                     | American Furniture Mart                   | The Rookery
Cincinnati | Kroger Building                  | Great American Tower at Queen City Square | PNC Tower
Cleveland  | National City Center             | 55 Public Square                          | Huntington Bank Building
Columbus   | Key Bank Building                |                                           | Leveque Tower
Dallas     | Reunion Tower                    | Bank of America Plaza                     | Three AT&T Plaza
... (25 rows omitted)

In [36]:
# polars
def first_pl(s):
    "Return the first element in an array."
    return s.item(0)

(sky_pl
 .sort('age', descending=True).pivot('material', index='city', values='name', aggregate_function='first').sort('city')
)#.where('city', 'San Francisco')

shape: (35, 4)
┌───────────────────┬──────────────────────────┬─────────────────────────┬─────────────────────────┐
│ city              ┆ steel                    ┆ concrete                ┆ mixed/composite         │
│ ---               ┆ ---                      ┆ ---                     ┆ ---                     │
│ str               ┆ str                      ┆ str                     ┆ str                     │
╞═══════════════════╪══════════════════════════╪═════════════════════════╪═════════════════════════╡
│ Atlanta           ┆ FlatironCity             ┆ Westin Peachtree Plaza  ┆ One Atlantic Center     │
│ Austin            ┆ University of Texas      ┆ One American Center     ┆ null                    │
│                   ┆ Tower                    ┆                         ┆                         │
│ Baltimore         ┆ Emerson Tower            ┆ Charles Towers North    ┆ null                    │
│                   ┆                          ┆ Apartment…              ┆                         │
│ Boston            ┆ Marriott's Custom House  ┆ Harbor Towers I         ┆ Ellison Building        │
│ Charlotte         ┆ Midtown Plaza            ┆ Bank of America         ┆ Hearst Tower            │
│                   ┆                          ┆ Corporate Cent…         ┆                         │
│ …                 ┆ …                        ┆ …                       ┆ …                       │
│ San Diego         ┆ Executive Complex        ┆ Meridian Condominiums   ┆ Electra                 │
│ San Francisco     ┆ Ferry Building           ┆ Coit Tower              ┆ Transamerica Pyramid    │
│ Seattle           ┆ Smith Tower              ┆ Continental Place       ┆ Unigard Financial       │
│                   ┆                          ┆                         ┆ Center                  │
│ St. Louis         ┆ Wainwright Building      ┆ KMOV Gateway Tower      ┆ One Metropolitan Square │
│ Sunny Isles Beach ┆ null                     ┆ The Pinnacle            ┆ null                    │
└───────────────────┴──────────────────────────┴─────────────────────────┴─────────────────────────┘

## Joins ##

In [37]:
drinks

Drink    | Cafe   | Price
Milk Tea | Asha   | 5.5
Espresso | Strada | 1.75
Latte    | Strada | 3.25
Espresso | FSM    | 2

In [38]:
# datascience
discounts = Table().with_columns(
    'Coupon % off', make_array(10, 25, 5),
    'Location', make_array('Asha', 'Strada', 'Asha')
)
discounts

Coupon % off | Location
10           | Asha
25           | Strada
5            | Asha

In [39]:
# polars
discounts_pl = pl.DataFrame([
    (pl.Series('values', [10, 25, 5])).alias('Coupon % off'),
    (pl.Series('values', ['Asha', 'Strada', 'Asha'])).alias('Location')
])
discounts_pl

shape: (3, 2)
┌──────────────┬──────────┐
│ Coupon % off ┆ Location │
│ ---          ┆ ---      │
│ i64          ┆ str      │
╞══════════════╪══════════╡
│ 10           ┆ Asha     │
│ 25           ┆ Strada   │
│ 5            ┆ Asha     │
└──────────────┴──────────┘

In [40]:
# datascience
combined = drinks.join('Cafe', discounts, 'Location')
combined

Cafe   | Drink    | Price | Coupon % off
Asha   | Milk Tea | 5.5   | 10
Asha   | Milk Tea | 5.5   | 5
Strada | Espresso | 1.75  | 25
Strada | Latte    | 3.25  | 25

In [41]:
# polars
combined_pl = drinks_pl.sort('Cafe').join(discounts_pl.sort('Location'), left_on='Cafe', right_on='Location')
combined_pl

shape: (4, 4)
┌──────────┬────────┬───────┬──────────────┐
│ Drink    ┆ Cafe   ┆ Price ┆ Coupon % off │
│ ---      ┆ ---    ┆ ---   ┆ ---          │
│ str      ┆ str    ┆ f64   ┆ i64          │
╞══════════╪════════╪═══════╪══════════════╡
│ Milk Tea ┆ Asha   ┆ 5.5   ┆ 10           │
│ Milk Tea ┆ Asha   ┆ 5.5   ┆ 5            │
│ Espresso ┆ Strada ┆ 1.75  ┆ 25           │
│ Latte    ┆ Strada ┆ 3.25  ┆ 25           │
└──────────┴────────┴───────┴──────────────┘

In [42]:
# datascience
discounted_frac = 1 - combined.column('Coupon % off') / 100
combined.with_column(
    'Discounted Price', 
    combined.column('Price') * discounted_frac
)

Cafe   | Drink    | Price | Coupon % off | Discounted Price
Asha   | Milk Tea | 5.5   | 10           | 4.95
Asha   | Milk Tea | 5.5   | 5            | 5.225
Strada | Espresso | 1.75  | 25           | 1.3125
Strada | Latte    | 3.25  | 25           | 2.4375

In [43]:
# polars
discounted_frac_pl = 1 - combined_pl.get_column('Coupon % off') / 100
combined_pl.with_columns((combined_pl.get_column('Price') * discounted_frac_pl).alias('Discounted Price'))

shape: (4, 5)
┌──────────┬────────┬───────┬──────────────┬──────────────────┐
│ Drink    ┆ Cafe   ┆ Price ┆ Coupon % off ┆ Discounted Price │
│ ---      ┆ ---    ┆ ---   ┆ ---          ┆ ---              │
│ str      ┆ str    ┆ f64   ┆ i64          ┆ f64              │
╞══════════╪════════╪═══════╪══════════════╪══════════════════╡
│ Milk Tea ┆ Asha   ┆ 5.5   ┆ 10           ┆ 4.95             │
│ Milk Tea ┆ Asha   ┆ 5.5   ┆ 5            ┆ 5.225            │
│ Espresso ┆ Strada ┆ 1.75  ┆ 25           ┆ 1.3125           │
│ Latte    ┆ Strada ┆ 3.25  ┆ 25           ┆ 2.4375           │
└──────────┴────────┴───────┴──────────────┴──────────────────┘

In [44]:
# datascience
drinks.join('Cafe', drinks, 'Cafe')

Cafe   | Drink    | Price | Drink_2  | Price_2
Asha   | Milk Tea | 5.5   | Milk Tea | 5.5
FSM    | Espresso | 2     | Espresso | 2
Strada | Espresso | 1.75  | Espresso | 1.75
Strada | Espresso | 1.75  | Latte    | 3.25
Strada | Latte    | 3.25  | Espresso | 1.75
Strada | Latte    | 3.25  | Latte    | 3.25

In [45]:
# polars
drinks_pl.sort('Cafe').join(drinks_pl.sort('Cafe'), on='Cafe')

shape: (6, 5)
┌──────────┬────────┬───────┬─────────────┬─────────────┐
│ Drink    ┆ Cafe   ┆ Price ┆ Drink_right ┆ Price_right │
│ ---      ┆ ---    ┆ ---   ┆ ---         ┆ ---         │
│ str      ┆ str    ┆ f64   ┆ str         ┆ f64         │
╞══════════╪════════╪═══════╪═════════════╪═════════════╡
│ Milk Tea ┆ Asha   ┆ 5.5   ┆ Milk Tea    ┆ 5.5         │
│ Espresso ┆ FSM    ┆ 2.0   ┆ Espresso    ┆ 2.0         │
│ Espresso ┆ Strada ┆ 1.75  ┆ Espresso    ┆ 1.75        │
│ Latte    ┆ Strada ┆ 3.25  ┆ Espresso    ┆ 1.75        │
│ Espresso ┆ Strada ┆ 1.75  ┆ Latte       ┆ 3.25        │
│ Latte    ┆ Strada ┆ 3.25  ┆ Latte       ┆ 3.25        │
└──────────┴────────┴───────┴─────────────┴─────────────┘