# Lecture 4 Notebook

In [1]:
# datascience
from datascience import *
import numpy as np

In [2]:
# polars
import polars as pl
from IPython.display import display

## Tables ##

A table is given a name (such as `nba`) in our programming environment so that we can perform operations on the whole table.

In [3]:
# datascience
# From Basketball Reference and ESPN
nba = Table.read_table('nba_salaries.csv')
nba

rank | name             | position | team                   | salary   | season
1    | Shaquille O'Neal | C        | Los Angeles Lakers     | 17142000 | 2000
2    | Kevin Garnett    | PF       | Minnesota Timberwolves | 16806000 | 2000
3    | Alonzo Mourning  | C        | Miami Heat             | 15004000 | 2000
4    | Juwan Howard     | PF       | Washington Wizards     | 15000000 | 2000
5    | Scottie Pippen   | SF       | Portland Trail Blazers | 14795000 | 2000
6    | Karl Malone      | PF       | Utah Jazz              | 14000000 | 2000
7    | Larry Johnson    | PF       | New York Knicks        | 11910000 | 2000
8    | Gary Payton      | PG       | Seattle SuperSonics    | 11020000 | 2000
9    | Rasheed Wallace  | PF       | Portland Trail Blazers | 10800000 | 2000
10   | Shawn Kemp       | C        | Cleveland Cavaliers    | 10780000 | 2000
... (10560 rows omitted)

In [4]:
# polars
# From Basketball Reference and ESPN
nba_pl = pl.read_csv('nba_salaries.csv')
nba_pl

shape: (10_570, 6)
┌──────┬─────────────────────────┬──────────┬────────────────────────┬──────────┬────────┐
│ rank ┆ name                    ┆ position ┆ team                   ┆ salary   ┆ season │
│ ---  ┆ ---                     ┆ ---      ┆ ---                    ┆ ---      ┆ ---    │
│ i64  ┆ str                     ┆ str      ┆ str                    ┆ i64      ┆ i64    │
╞══════╪═════════════════════════╪══════════╪════════════════════════╪══════════╪════════╡
│ 1    ┆ Shaquille O'Neal        ┆ C        ┆ Los Angeles Lakers     ┆ 17142000 ┆ 2000   │
│ 2    ┆ Kevin Garnett           ┆ PF       ┆ Minnesota Timberwolves ┆ 16806000 ┆ 2000   │
│ 3    ┆ Alonzo Mourning         ┆ C        ┆ Miami Heat             ┆ 15004000 ┆ 2000   │
│ 4    ┆ Juwan Howard            ┆ PF       ┆ Washington Wizards     ┆ 15000000 ┆ 2000   │
│ 5    ┆ Scottie Pippen          ┆ SF       ┆ Portland Trail Blazers ┆ 14795000 ┆ 2000   │
│ …    ┆ …                       ┆ …        ┆ …                      ┆ …        ┆ …      │
│ 471  ┆ Olivier-Maxence Prosper ┆ PF       ┆ Memphis Grizzlies      ┆ 527879   ┆ 2026   │
│ 472  ┆ Tyus Jones              ┆ PG       ┆ Denver Nuggets         ┆ 514682   ┆ 2026   │
│ 473  ┆ Amari Williams          ┆ PF       ┆ Boston Celtics         ┆ 490128   ┆ 2026   │
│ 474  ┆ Myron Gardner           ┆ SF       ┆ Miami Heat             ┆ 395029   ┆ 2026   │
│ 475  ┆ Ryan Nembhard           ┆ PG       ┆ Dallas Mavericks       ┆ 321875   ┆ 2026   │
└──────┴─────────────────────────┴──────────┴────────────────────────┴──────────┴────────┘

Manipulating the table creates a new table, but doesn't change/lose the original.

In [5]:
# datascience
nba.select('name')

name
Shaquille O'Neal
Kevin Garnett
Alonzo Mourning
Juwan Howard
Scottie Pippen
Karl Malone
Larry Johnson
Gary Payton
Rasheed Wallace
Shawn Kemp
... (10560 rows omitted)

In [6]:
# polars
nba_pl.select('name')

shape: (10_570, 1)
┌─────────────────────────┐
│ name                    │
│ ---                     │
│ str                     │
╞═════════════════════════╡
│ Shaquille O'Neal        │
│ Kevin Garnett           │
│ Alonzo Mourning         │
│ Juwan Howard            │
│ Scottie Pippen          │
│ …                       │
│ Olivier-Maxence Prosper │
│ Tyus Jones              │
│ Amari Williams          │
│ Myron Gardner           │
│ Ryan Nembhard           │
└─────────────────────────┘

In [7]:
nba

rank | name             | position | team                   | salary   | season
1    | Shaquille O'Neal | C        | Los Angeles Lakers     | 17142000 | 2000
2    | Kevin Garnett    | PF       | Minnesota Timberwolves | 16806000 | 2000
3    | Alonzo Mourning  | C        | Miami Heat             | 15004000 | 2000
4    | Juwan Howard     | PF       | Washington Wizards     | 15000000 | 2000
5    | Scottie Pippen   | SF       | Portland Trail Blazers | 14795000 | 2000
6    | Karl Malone      | PF       | Utah Jazz              | 14000000 | 2000
7    | Larry Johnson    | PF       | New York Knicks        | 11910000 | 2000
8    | Gary Payton      | PG       | Seattle SuperSonics    | 11020000 | 2000
9    | Rasheed Wallace  | PF       | Portland Trail Blazers | 10800000 | 2000
10   | Shawn Kemp       | C        | Cleveland Cavaliers    | 10780000 | 2000
... (10560 rows omitted)

In [8]:
'nba'

'nba'

In [9]:
# datascience
nba.drop('rank', 'position')

name             | team                   | salary   | season
Shaquille O'Neal | Los Angeles Lakers     | 17142000 | 2000
Kevin Garnett    | Minnesota Timberwolves | 16806000 | 2000
Alonzo Mourning  | Miami Heat             | 15004000 | 2000
Juwan Howard     | Washington Wizards     | 15000000 | 2000
Scottie Pippen   | Portland Trail Blazers | 14795000 | 2000
Karl Malone      | Utah Jazz              | 14000000 | 2000
Larry Johnson    | New York Knicks        | 11910000 | 2000
Gary Payton      | Seattle SuperSonics    | 11020000 | 2000
Rasheed Wallace  | Portland Trail Blazers | 10800000 | 2000
Shawn Kemp       | Cleveland Cavaliers    | 10780000 | 2000
... (10560 rows omitted)

In [10]:
# polars
nba_pl.drop('rank', 'position')

shape: (10_570, 4)
┌─────────────────────────┬────────────────────────┬──────────┬────────┐
│ name                    ┆ team                   ┆ salary   ┆ season │
│ ---                     ┆ ---                    ┆ ---      ┆ ---    │
│ str                     ┆ str                    ┆ i64      ┆ i64    │
╞═════════════════════════╪════════════════════════╪══════════╪════════╡
│ Shaquille O'Neal        ┆ Los Angeles Lakers     ┆ 17142000 ┆ 2000   │
│ Kevin Garnett           ┆ Minnesota Timberwolves ┆ 16806000 ┆ 2000   │
│ Alonzo Mourning         ┆ Miami Heat             ┆ 15004000 ┆ 2000   │
│ Juwan Howard            ┆ Washington Wizards     ┆ 15000000 ┆ 2000   │
│ Scottie Pippen          ┆ Portland Trail Blazers ┆ 14795000 ┆ 2000   │
│ …                       ┆ …                      ┆ …        ┆ …      │
│ Olivier-Maxence Prosper ┆ Memphis Grizzlies      ┆ 527879   ┆ 2026   │
│ Tyus Jones              ┆ Denver Nuggets         ┆ 514682   ┆ 2026   │
│ Amari Williams          ┆ Boston Celtics         ┆ 490128   ┆ 2026   │
│ Myron Gardner           ┆ Miami Heat             ┆ 395029   ┆ 2026   │
│ Ryan Nembhard           ┆ Dallas Mavericks       ┆ 321875   ┆ 2026   │
└─────────────────────────┴────────────────────────┴──────────┴────────┘

In [11]:
# datascience
nba.sort('name')

rank | name        | position | team               | salary  | season
180  | A.C. Green  | PF       | Miami Heat         | 2250000 | 2001
355  | A.J. Guyton | PG       | Chicago Bulls      | 316000  | 2001
384  | A.J. Guyton | PG       | Chicago Bulls      | 465000  | 2002
454  | A.J. Lawson | SG       | Dallas Mavericks   | 1000000 | 2024
365  | A.J. Lawson | SG       | Toronto Raptors    | 2120693 | 2025
389  | A.J. Lawson | SG       | Toronto Raptors    | 2270735 | 2026
436  | A.J. Price  | PG       | Indiana Pacers     | 457588  | 2010
441  | A.J. Price  | PG       | Indiana Pacers     | 762195  | 2011
410  | A.J. Price  | PG       | Indiana Pacers     | 854389  | 2012
436  | A.J. Price  | PG       | Washington Wizards | 854389  | 2013
... (10560 rows omitted)

In [12]:
# polars
nba_pl.sort('name')

shape: (10_570, 6)
┌──────┬────────────────────┬──────────┬─────────────────────┬──────────┬────────┐
│ rank ┆ name               ┆ position ┆ team                ┆ salary   ┆ season │
│ ---  ┆ ---                ┆ ---      ┆ ---                 ┆ ---      ┆ ---    │
│ i64  ┆ str                ┆ str      ┆ str                 ┆ i64      ┆ i64    │
╞══════╪════════════════════╪══════════╪═════════════════════╪══════════╪════════╡
│ 180  ┆ A.C. Green         ┆ PF       ┆ Miami Heat          ┆ 2250000  ┆ 2001   │
│ 355  ┆ A.J. Guyton        ┆ PG       ┆ Chicago Bulls       ┆ 316000   ┆ 2001   │
│ 384  ┆ A.J. Guyton        ┆ PG       ┆ Chicago Bulls       ┆ 465000   ┆ 2002   │
│ 454  ┆ A.J. Lawson        ┆ SG       ┆ Dallas Mavericks    ┆ 1000000  ┆ 2024   │
│ 365  ┆ A.J. Lawson        ┆ SG       ┆ Toronto Raptors     ┆ 2120693  ┆ 2025   │
│ …    ┆ …                  ┆ …        ┆ …                   ┆ …        ┆ …      │
│ 46   ┆ Zydrunas Ilgauskas ┆ C        ┆ Cleveland Cavaliers ┆ 9442697  ┆ 2007   │
│ 51   ┆ Zydrunas Ilgauskas ┆ C        ┆ Cleveland Cavaliers ┆ 10142156 ┆ 2008   │
│ 53   ┆ Zydrunas Ilgauskas ┆ C        ┆ Cleveland Cavaliers ┆ 10841615 ┆ 2009   │
│ 343  ┆ Zydrunas Ilgauskas ┆ C        ┆ Cleveland Cavaliers ┆ 925000   ┆ 2010   │
│ 309  ┆ Zydrunas Ilgauskas ┆ C        ┆ Miami Heat          ┆ 1352181  ┆ 2011   │
└──────┴────────────────────┴──────────┴─────────────────────┴──────────┴────────┘

In [13]:
# datascience
nba.where('name', "Shaquille O'Neal")

rank | name             | position | team               | salary   | season
1    | Shaquille O'Neal | C        | Los Angeles Lakers | 17142000 | 2000
2    | Shaquille O'Neal | C        | Los Angeles Lakers | 19285000 | 2001
2    | Shaquille O'Neal | C        | Los Angeles Lakers | 21428000 | 2002
2    | Shaquille O'Neal | C        | Los Angeles Lakers | 23571000 | 2003
2    | Shaquille O'Neal | C        | Los Angeles Lakers | 26571000 | 2004
1    | Shaquille O'Neal | C        | Miami Heat         | 29464000 | 2005
1    | Shaquille O'Neal | C        | Miami Heat         | 20000000 | 2006
2    | Shaquille O'Neal | C        | Miami Heat         | 20000000 | 2007
2    | Shaquille O'Neal | C        | Phoenix Suns       | 21000000 | 2008
5    | Shaquille O'Neal | C        | Phoenix Suns       | 21000000 | 2009
... (2 rows omitted)

In [14]:
# polars
nba_pl.filter((pl.col('name') == ("Shaquille O'Neal")))

shape: (12, 6)
┌──────┬──────────────────┬──────────┬─────────────────────┬──────────┬────────┐
│ rank ┆ name             ┆ position ┆ team                ┆ salary   ┆ season │
│ ---  ┆ ---              ┆ ---      ┆ ---                 ┆ ---      ┆ ---    │
│ i64  ┆ str              ┆ str      ┆ str                 ┆ i64      ┆ i64    │
╞══════╪══════════════════╪══════════╪═════════════════════╪══════════╪════════╡
│ 1    ┆ Shaquille O'Neal ┆ C        ┆ Los Angeles Lakers  ┆ 17142000 ┆ 2000   │
│ 2    ┆ Shaquille O'Neal ┆ C        ┆ Los Angeles Lakers  ┆ 19285000 ┆ 2001   │
│ 2    ┆ Shaquille O'Neal ┆ C        ┆ Los Angeles Lakers  ┆ 21428000 ┆ 2002   │
│ 2    ┆ Shaquille O'Neal ┆ C        ┆ Los Angeles Lakers  ┆ 23571000 ┆ 2003   │
│ 2    ┆ Shaquille O'Neal ┆ C        ┆ Los Angeles Lakers  ┆ 26571000 ┆ 2004   │
│ …    ┆ …                ┆ …        ┆ …                   ┆ …        ┆ …      │
│ 2    ┆ Shaquille O'Neal ┆ C        ┆ Miami Heat          ┆ 20000000 ┆ 2007   │
│ 2    ┆ Shaquille O'Neal ┆ C        ┆ Phoenix Suns        ┆ 21000000 ┆ 2008   │
│ 5    ┆ Shaquille O'Neal ┆ C        ┆ Phoenix Suns        ┆ 21000000 ┆ 2009   │
│ 5    ┆ Shaquille O'Neal ┆ C        ┆ Cleveland Cavaliers ┆ 21000000 ┆ 2010   │
│ 311  ┆ Shaquille O'Neal ┆ C        ┆ Boston Celtics      ┆ 1352181  ┆ 2011   │
└──────┴──────────────────┴──────────┴─────────────────────┴──────────┴────────┘

In [15]:
# datascience
nba.where('position', 'PG')

rank | name             | position | team                   | salary   | season
8    | Gary Payton      | PG       | Seattle SuperSonics    | 11020000 | 2000
11   | Damon Stoudamire | PG       | Portland Trail Blazers | 10125000 | 2000
20   | Stephon Marbury  | PG       | New Jersey Nets        | 9000000  | 2000
24   | Nick Van Exel    | PG       | Denver Nuggets         | 8354000  | 2000
26   | Terrell Brandon  | PG       | Minnesota Timberwolves | 7400000  | 2000
34   | Jason Kidd       | PG       | Phoenix Suns           | 6858000  | 2000
35   | Kenny Anderson   | PG       | Boston Celtics         | 6680000  | 2000
39   | Steve Nash       | PG       | Dallas Mavericks       | 5500000  | 2000
55   | Charlie Ward     | PG       | New York Knicks        | 4540000  | 2000
58   | Mookie Blaylock  | PG       | Golden State Warriors  | 4200000  | 2000
... (1945 rows omitted)

In [16]:
# polars
nba_pl.filter((pl.col('position') == ('PG')))

shape: (1_955, 6)
┌──────┬──────────────────┬──────────┬────────────────────────┬──────────┬────────┐
│ rank ┆ name             ┆ position ┆ team                   ┆ salary   ┆ season │
│ ---  ┆ ---              ┆ ---      ┆ ---                    ┆ ---      ┆ ---    │
│ i64  ┆ str              ┆ str      ┆ str                    ┆ i64      ┆ i64    │
╞══════╪══════════════════╪══════════╪════════════════════════╪══════════╪════════╡
│ 8    ┆ Gary Payton      ┆ PG       ┆ Seattle SuperSonics    ┆ 11020000 ┆ 2000   │
│ 11   ┆ Damon Stoudamire ┆ PG       ┆ Portland Trail Blazers ┆ 10125000 ┆ 2000   │
│ 20   ┆ Stephon Marbury  ┆ PG       ┆ New Jersey Nets        ┆ 9000000  ┆ 2000   │
│ 24   ┆ Nick Van Exel    ┆ PG       ┆ Denver Nuggets         ┆ 8354000  ┆ 2000   │
│ 26   ┆ Terrell Brandon  ┆ PG       ┆ Minnesota Timberwolves ┆ 7400000  ┆ 2000   │
│ …    ┆ …                ┆ …        ┆ …                      ┆ …        ┆ …      │
│ 462  ┆ Cameron Payne    ┆ PG       ┆ Philadelphia 76ers     ┆ 712637   ┆ 2026   │
│ 467  ┆ Quenton Jackson  ┆ PG       ┆ Indiana Pacers         ┆ 601553   ┆ 2026   │
│ 469  ┆ Jamaree Bouyea   ┆ PG       ┆ Phoenix Suns           ┆ 574210   ┆ 2026   │
│ 472  ┆ Tyus Jones       ┆ PG       ┆ Denver Nuggets         ┆ 514682   ┆ 2026   │
│ 475  ┆ Ryan Nembhard    ┆ PG       ┆ Dallas Mavericks       ┆ 321875   ┆ 2026   │
└──────┴──────────────────┴──────────┴────────────────────────┴──────────┴────────┘

Because each operation creates a new table, multiple operations can be applied.

In [17]:
# datascience
nba.where('position', 'PG').drop('rank', 'position')

name             | team                   | salary   | season
Gary Payton      | Seattle SuperSonics    | 11020000 | 2000
Damon Stoudamire | Portland Trail Blazers | 10125000 | 2000
Stephon Marbury  | New Jersey Nets        | 9000000  | 2000
Nick Van Exel    | Denver Nuggets         | 8354000  | 2000
Terrell Brandon  | Minnesota Timberwolves | 7400000  | 2000
Jason Kidd       | Phoenix Suns           | 6858000  | 2000
Kenny Anderson   | Boston Celtics         | 6680000  | 2000
Steve Nash       | Dallas Mavericks       | 5500000  | 2000
Charlie Ward     | New York Knicks        | 4540000  | 2000
Mookie Blaylock  | Golden State Warriors  | 4200000  | 2000
... (1945 rows omitted)

In [18]:
# polars
nba_pl.filter((pl.col('position') == ('PG'))).drop('rank', 'position')

shape: (1_955, 4)
┌──────────────────┬────────────────────────┬──────────┬────────┐
│ name             ┆ team                   ┆ salary   ┆ season │
│ ---              ┆ ---                    ┆ ---      ┆ ---    │
│ str              ┆ str                    ┆ i64      ┆ i64    │
╞══════════════════╪════════════════════════╪══════════╪════════╡
│ Gary Payton      ┆ Seattle SuperSonics    ┆ 11020000 ┆ 2000   │
│ Damon Stoudamire ┆ Portland Trail Blazers ┆ 10125000 ┆ 2000   │
│ Stephon Marbury  ┆ New Jersey Nets        ┆ 9000000  ┆ 2000   │
│ Nick Van Exel    ┆ Denver Nuggets         ┆ 8354000  ┆ 2000   │
│ Terrell Brandon  ┆ Minnesota Timberwolves ┆ 7400000  ┆ 2000   │
│ …                ┆ …                      ┆ …        ┆ …      │
│ Cameron Payne    ┆ Philadelphia 76ers     ┆ 712637   ┆ 2026   │
│ Quenton Jackson  ┆ Indiana Pacers         ┆ 601553   ┆ 2026   │
│ Jamaree Bouyea   ┆ Phoenix Suns           ┆ 574210   ┆ 2026   │
│ Tyus Jones       ┆ Denver Nuggets         ┆ 514682   ┆ 2026   │
│ Ryan Nembhard    ┆ Dallas Mavericks       ┆ 321875   ┆ 2026   │
└──────────────────┴────────────────────────┴──────────┴────────┘

### **SUMMARIZE**: Constructing a new version of table `t`…

What does each table method do, in "plain English"?

| Num | Table method | Example with `nba` table |
| --- | --- | --- | 
| 1 | `t.select(label)` | `nba.select('position')` |
| 2 | `t.drop(label)` | `nba.drop('position')` |
| 3 | `t.sort(label)` |  `nba.sort('position')` | 
| 4 | `t.where(label, condition)` | `nba.where('position', 'PG')` |

<br/><br/><br/><br/>



The result of applying operations is a table, which can also be given a name (e.g., `point_guards`) in our programming environment.

In [19]:
# datascience
point_guards = nba.where('position', 'PG').drop('rank', 'position')
point_guards

name             | team                   | salary   | season
Gary Payton      | Seattle SuperSonics    | 11020000 | 2000
Damon Stoudamire | Portland Trail Blazers | 10125000 | 2000
Stephon Marbury  | New Jersey Nets        | 9000000  | 2000
Nick Van Exel    | Denver Nuggets         | 8354000  | 2000
Terrell Brandon  | Minnesota Timberwolves | 7400000  | 2000
Jason Kidd       | Phoenix Suns           | 6858000  | 2000
Kenny Anderson   | Boston Celtics         | 6680000  | 2000
Steve Nash       | Dallas Mavericks       | 5500000  | 2000
Charlie Ward     | New York Knicks        | 4540000  | 2000
Mookie Blaylock  | Golden State Warriors  | 4200000  | 2000
... (1945 rows omitted)

In [20]:
# polars
point_guards_pl = nba_pl.filter((pl.col('position') == ('PG'))).drop('rank', 'position')
point_guards_pl

shape: (1_955, 4)
┌──────────────────┬────────────────────────┬──────────┬────────┐
│ name             ┆ team                   ┆ salary   ┆ season │
│ ---              ┆ ---                    ┆ ---      ┆ ---    │
│ str              ┆ str                    ┆ i64      ┆ i64    │
╞══════════════════╪════════════════════════╪══════════╪════════╡
│ Gary Payton      ┆ Seattle SuperSonics    ┆ 11020000 ┆ 2000   │
│ Damon Stoudamire ┆ Portland Trail Blazers ┆ 10125000 ┆ 2000   │
│ Stephon Marbury  ┆ New Jersey Nets        ┆ 9000000  ┆ 2000   │
│ Nick Van Exel    ┆ Denver Nuggets         ┆ 8354000  ┆ 2000   │
│ Terrell Brandon  ┆ Minnesota Timberwolves ┆ 7400000  ┆ 2000   │
│ …                ┆ …                      ┆ …        ┆ …      │
│ Cameron Payne    ┆ Philadelphia 76ers     ┆ 712637   ┆ 2026   │
│ Quenton Jackson  ┆ Indiana Pacers         ┆ 601553   ┆ 2026   │
│ Jamaree Bouyea   ┆ Phoenix Suns           ┆ 574210   ┆ 2026   │
│ Tyus Jones       ┆ Denver Nuggets         ┆ 514682   ┆ 2026   │
│ Ryan Nembhard    ┆ Dallas Mavericks       ┆ 321875   ┆ 2026   │
└──────────────────┴────────────────────────┴──────────┴────────┘

After running the below cell, in what "order" are the rows in the resulting table sorted?

In [21]:
# datascience
point_guards.where('season', 2026).sort('name').sort('team')

name             | team              | salary   | season
CJ McCollum      | Atlanta Hawks     | 30666666 | 2026
Gabe Vincent     | Atlanta Hawks     | 11500000 | 2026
Keaton Wallace   | Atlanta Hawks     | 2296274  | 2026
Payton Pritchard | Boston Celtics    | 7232143  | 2026
Egor Demin       | Brooklyn Nets     | 6889200  | 2026
Nolan Traore     | Brooklyn Nets     | 3811560  | 2026
LaMelo Ball      | Charlotte Hornets | 37958760 | 2026
Tre Mann         | Charlotte Hornets | 8000000  | 2026
Josh Giddey      | Chicago Bulls     | 25000000 | 2026
Rob Dillingham   | Chicago Bulls     | 6576120  | 2026
... (61 rows omitted)

In [22]:
# polars
point_guards_pl.filter((pl.col('season') == (2026))).sort('name').sort('team')

shape: (71, 4)
┌──────────────────┬────────────────────┬──────────┬────────┐
│ name             ┆ team               ┆ salary   ┆ season │
│ ---              ┆ ---                ┆ ---      ┆ ---    │
│ str              ┆ str                ┆ i64      ┆ i64    │
╞══════════════════╪════════════════════╪══════════╪════════╡
│ CJ McCollum      ┆ Atlanta Hawks      ┆ 30666666 ┆ 2026   │
│ Gabe Vincent     ┆ Atlanta Hawks      ┆ 11500000 ┆ 2026   │
│ Keaton Wallace   ┆ Atlanta Hawks      ┆ 2296274  ┆ 2026   │
│ Payton Pritchard ┆ Boston Celtics     ┆ 7232143  ┆ 2026   │
│ Egor Demin       ┆ Brooklyn Nets      ┆ 6889200  ┆ 2026   │
│ …                ┆ …                  ┆ …        ┆ …      │
│ Jamal Shead      ┆ Toronto Raptors    ┆ 1955377  ┆ 2026   │
│ Isaiah Collier   ┆ Utah Jazz          ┆ 2638200  ┆ 2026   │
│ Keyonte George   ┆ Utah Jazz          ┆ 4278960  ┆ 2026   │
│ Bub Carrington   ┆ Washington Wizards ┆ 4677600  ┆ 2026   │
│ Trae Young       ┆ Washington Wizards ┆ 46394100 ┆ 2026   │
└──────────────────┴────────────────────┴──────────┴────────┘

Sorting can be performed in descending order as well.

In [23]:
# datascience
point_guards.where('season', 2026).sort('salary').show(10)

In [24]:
# polars
point_guards_pl.filter((pl.col('season') == (2026))).sort('salary').head(10)

shape: (10, 4)
┌─────────────────┬────────────────────────┬─────────┬────────┐
│ name            ┆ team                   ┆ salary  ┆ season │
│ ---             ┆ ---                    ┆ ---     ┆ ---    │
│ str             ┆ str                    ┆ i64     ┆ i64    │
╞═════════════════╪════════════════════════╪═════════╪════════╡
│ Ryan Nembhard   ┆ Dallas Mavericks       ┆ 321875  ┆ 2026   │
│ Tyus Jones      ┆ Denver Nuggets         ┆ 514682  ┆ 2026   │
│ Jamaree Bouyea  ┆ Phoenix Suns           ┆ 574210  ┆ 2026   │
│ Quenton Jackson ┆ Indiana Pacers         ┆ 601553  ┆ 2026   │
│ Cameron Payne   ┆ Philadelphia 76ers     ┆ 712637  ┆ 2026   │
│ Mike Conley     ┆ Minnesota Timberwolves ┆ 725834  ┆ 2026   │
│ Pat Spencer     ┆ Golden State Warriors  ┆ 857804  ┆ 2026   │
│ Jevon Carter    ┆ Orlando Magic          ┆ 871000  ┆ 2026   │
│ Tyrese Proctor  ┆ Cleveland Cavaliers    ┆ 1272870 ┆ 2026   │
│ Jamal Shead     ┆ Toronto Raptors        ┆ 1955377 ┆ 2026   │
└─────────────────┴────────────────────────┴─────────┴────────┘

Who was the highest-paid Point Guard in 2026?

In [25]:
# datascience
point_guards.where('season', 2026).sort('salary', descending=True).show(10)

In [26]:
# polars
point_guards_pl.filter((pl.col('season') == (2026))).sort('salary', descending=True).head(10)

shape: (10, 4)
┌─────────────────────────┬───────────────────────┬──────────┬────────┐
│ name                    ┆ team                  ┆ salary   ┆ season │
│ ---                     ┆ ---                   ┆ ---      ┆ ---    │
│ str                     ┆ str                   ┆ i64      ┆ i64    │
╞═════════════════════════╪═══════════════════════╪══════════╪════════╡
│ Stephen Curry           ┆ Golden State Warriors ┆ 59606817 ┆ 2026   │
│ Luka Doncic             ┆ Los Angeles Lakers    ┆ 54126450 ┆ 2026   │
│ Trae Young              ┆ Washington Wizards    ┆ 46394100 ┆ 2026   │
│ Cade Cunningham         ┆ Detroit Pistons       ┆ 46394100 ┆ 2026   │
│ Jamal Murray            ┆ Denver Nuggets        ┆ 46394100 ┆ 2026   │
│ Ja Morant               ┆ Memphis Grizzlies     ┆ 39446090 ┆ 2026   │
│ Darius Garland          ┆ LA Clippers           ┆ 39446090 ┆ 2026   │
│ James Harden            ┆ Cleveland Cavaliers   ┆ 39446090 ┆ 2026   │
│ Shai Gilgeous-Alexander ┆ Oklahoma City Thunder ┆ 38333050 ┆ 2026   │
│ Tyrese Maxey            ┆ Philadelphia 76ers    ┆ 37958760 ┆ 2026   │
└─────────────────────────┴───────────────────────┴──────────┴────────┘

Stephen Curry of the Golden State Warriors

<img src="https://images.wallpapersden.com/image/download/stephen-curry-golden-state-warriors-basketball_Z2ZsaGiUmZqaraWkpJRmbmdlrWZlbWU.jpg" width=400px alt="A young Stephen Curry of the Golden State Warriors shooting a three-pointer">

---

## Types ##

Every value has a type.

In [27]:
type(10)

int

In [28]:
a = 10

In [29]:
a

10

In [30]:
type(a)

int

In [31]:
type(4.5)

float

In [32]:
type('abc')

str

In [33]:
type(nba)

datascience.tables.Table

In [34]:
# datascience
type(Table.read_table('nba_salaries.csv'))

datascience.tables.Table

In [35]:
# polars
type(pl.read_csv('nba_salaries.csv'))

polars.dataframe.frame.DataFrame

In [36]:
type(True)

bool

In [37]:
type(abs(-5))

int

In [38]:
type(abs)

builtin_function_or_method

---

## Arrays ##

In [39]:
# datascience
first_four = make_array(1, 2, 3, 4)

In [40]:
# polars
first_four_pl = pl.Series('values', [1, 2, 3, 4])

In [41]:
first_four

array([1, 2, 3, 4])

In [42]:
# datascience
array([1, 2, 3, 4])

NameError: name 'array' is not defined

In [43]:
# polars
array([1, 2, 3, 4])

NameError: name 'array' is not defined

In [44]:
# datascience
from numpy import array

In [45]:
# polars
# np.array and make_array are a named pl.Series. This import is not used.

In [46]:
array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [47]:
first_four

array([1, 2, 3, 4])

In [48]:
first_four * 2

array([2, 4, 6, 8])

In [49]:
first_four ** 2

array([ 1,  4,  9, 16])

In [50]:
(first_four + 1) ** 2

array([ 4,  9, 16, 25])

In [51]:
# datascience
first_four # array is unchanged, just like when we call show/select/drop on Table

array([1, 2, 3, 4])

In [52]:
# polars
first_four_pl # array is unchanged, just like when we call show/select/drop on Table

shape: (4,)
Series: 'values' [i64]
[
	1
	2
	3
	4
]

In [53]:
# datascience
next_four = make_array(5, 6, 7, 8)

In [54]:
# polars
next_four_pl = pl.Series('values', [5, 6, 7, 8])

In [55]:
next_four

array([5, 6, 7, 8])

In [56]:
first_four + next_four

array([ 6,  8, 10, 12])

In [57]:
# datascience
only_three = make_array(5, 6, 7)

In [58]:
# polars
only_three_pl = pl.Series('values', [5, 6, 7])

In [59]:
# datascience
# This line will cause an error 
first_four + only_three

ValueError: operands could not be broadcast together with shapes (4,) (3,)

In [60]:
# polars
# This line will cause an error 
first_four_pl + only_three_pl

InvalidOperationError: cannot do arithmetic operation on series of different lengths: got 4 and 3

In [61]:
# datascience
str_array = make_array('ha', 'he', 'hi')

In [62]:
# polars
str_array_pl = pl.Series('values', ['ha', 'he', 'hi'])

In [63]:
str_array

array(['ha', 'he', 'hi'],
      dtype='<U2')

In [64]:
str_array + 'heh'

array(['haheh', 'heheh', 'hiheh'],
      dtype='<U5')

In [65]:
# datascience
str_array * 4

TypeError: The 'out' kwarg is necessary when using the string multiply ufunc directly. Use numpy.strings.multiply to multiply strings without specifying 'out'.

In [66]:
# polars
str_array_pl * 4

TypeError: cannot do arithmetic with Series of dtype: String and argument of type: 'str'

In [67]:
next_four

array([5, 6, 7, 8])

In [68]:
next_four.item(0)

5

In [69]:
# datascience
next_four.item(4)

IndexError: index 4 is out of bounds for axis 0 with size 4

In [70]:
# polars
next_four_pl.item(4)

IndexError: index 4 is out of bounds for sequence of length 4

In [71]:
sum(next_four)

26

In [72]:
# datascience
np.average(next_four)

6.5

In [73]:
# polars
(next_four_pl).mean()

6.5

In [74]:
len(next_four)

4

## Quick Demo: Numbers and Strings

### Quick Demo: Numbers (Section 4.1)

In [75]:
10 * 3    # int

30

In [76]:
10 / 3    # float

3.3333333333333335

In [77]:
75892745.215489247589274985712

75892745.21548925

In [78]:
75892745.215489247589274985712 - 75892745.21548925

0.0

In [79]:
6 / 4

1.5

In [80]:
6 / 4000

0.0015

In [81]:
6 / 400000000000000000000000000000000000000000000000000000000

1.5e-56

In [82]:
400000000000000000000000000000000000000000000000000000000 * 1.5e-56

6.0

Just like in calculators, scientific notation of $1.5 \times 10^{-56}$ is written as

In [83]:
1.5e-56

1.5e-56

### Quick Demo: Strings (Section 4.2)

More in textbook!

In [84]:
'straw' + 'berry' # concatenation

'strawberry'

In [85]:
'Chris' + 'Paul' # spaces aren't added for you

'ChrisPaul'

In [86]:
'Chris' + ' ' + 'Paul'

'Chris Paul'

In [87]:
x = 'straw'
y = 'berry'
x + y

'strawberry'

In [88]:
'ha' * 100

'hahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahaha'

In [89]:
# datascience
'lo' * 5.5

TypeError: can't multiply sequence by non-int of type 'float'

In [90]:
# polars
'lo' * 5.5

TypeError: can't multiply sequence by non-int of type 'float'

## Longer Demo: Numbers (Section 4.1)

In [91]:
30

30

In [92]:
10 * 3    # int

30

In [93]:
10 / 3    # float

3.3333333333333335

In [94]:
10 / 2

5.0

In [95]:
10 ** 3

1000

In [96]:
10 ** 0.5

3.1622776601683795

In [97]:
import sys
sys.set_int_max_str_digits(0)
1234567 ** 890

2805763342107369230793809808310885724030151698643898788380662816980113897853769505682553341995361840866283163839674938063847465098181599413516030923830315020297429114484842472806037601633183177392342419552281446098882333113360498936060689417981060580169581781517081000887466986920196787365735472976637384790660527656183529108057677628812897898917415727467403873251697100284318113613171090832770107627373429297578100452541331137972394395518879748252497629953169189742546688743838014842998797222488578482742255590278830326264415887042424349338336685586108014796843647297854686632059611017792593114133643766176826645471505135284339608286440790108605114687261446214106703238304626747430320283170505623593598192482183253323227473361217459497593514576103139354263910235117552944853835259328240635891089203247501395301794244132584186874755797831852390704417457044048557568618633160284149583340352686512009611975784239859264336878392387482791049156912854159715516214706166214466230037339823780492774337274675800289580696315819494418004733412855205155027918058344891850668473780787520539851110601937177777258527635476258052342827179765186381834973522303136829852834242679559888371990546547773735142872611383102742753311234958929602179017609453450788021576889968090558526946002867067155433937025164603278496325064732080655085967120552122358643425906339419468088785812576641170399781555198518542228755764090812514788163758877228031474626249982320173230513790766211051807071509018394299594496298553425032888639575233308427922962072691110016410832613254845558533479779137394546533348267260208654147664661662489837722166465535984470300130195361526724657999247737664119545166367970118960539653700728246780841243422865927822029745430687779341494835511048331091708435435810632677284968867671217350609932555531424276428454845446681148799804144451127195396670373733155503688440766376117308145231339204514518114182442669726926958460263504747823171357759585770665369994677944653246927717262087721616975390825217507408220510861018634338133464060418295047933927635868626199925788463191380080935701443847346532746838349449833204183719520425273508461427363268810901816439207520602455792069406367821658839121277649227555623273564677301331404339603368354187279170542954088017099056552277230318062383216542056927422226999811205450549485589246237819874869638917303541644714356081602468616512144027808621669917967523298847733280998188849126660410144516840751121177122218727312917235905337333060556516611924333661893530040067042505379294125436401184352256775565463142705637306783871882313794728831427529583150846149427004802322087788357968992264438692993009809883875465518646172470495839410492599060455716367637440364630131471750106709132465895371670412945256073822697903510522211765697295922053593229276419226531331408317896936830655815873666355197305378708964668209899291344705444276333578719323904170952074328643811404544256843025709425474387814973960542018630128201161272329024792011740745530212579878161378961127918038096648026162029808878747866210894432543002029434565613132355043777385763831238060952363449797871761622541777453653784081456719940419766751192867804269268505636574832199689538986715250742630200523490339094085425178568698903268320220973567490288420919261018482168538171910000711992076873681129307598675285503345960161016391830728260326693428202177160119543736800344297771481079627076988031975978575895647654221558620092991884687091862613605722144271490738163190650508558761186844994717152403269557878581184075275936408939256017646715559306260196259010170427037361073267573147026510628695621128132172515464076418742940103113964611681699407950967774413428184355249041334714765827480675899800235537773385443229622067233523354213261412403375030932576886654499317808172035910623439488923497729990034132955991616175315301110003136655552464696428279778365477406164307525011119783055047664864798818426307604172381073695798688377889193415423645042188927398145864445871680431617772823584658707705057426132797633601281478887542871708884776132993498113629791075212269131263135104211901928478309667400642477145201362433365658578707267018122388906853103264797837550314906826327964589811537800151348078278689526492266541600168152334174087551992509222975658050902151573849522445074588731109036554789680280345720046009120507928152632018078697710120218368147570599141031673300682348326156497244011574817802187099834880327346210624556369660018678859929271654108596951193479453034452114779847850504280525490303492730731848704497321639579545359051407002629069912400518470707512308477494989006390249351273561453957767103749105099486859441823499120103359974562095361878219993785312682108204349115081403854873968693651144816992008787094413654541840750267945428940655147102103776877924495354589674471203663800973702240269677784610346010441824261817763592599870546594987128802020889878623694800247575251661439276157008847529529237192162577463356503617323132760079688627706444510425779441871297035026396768851129501722454220316418777074912838238391162658683371634959415544181384058154251960767217101632139258312150904777623156788937309713540569306765232165671618935868039816292110221657560493742908804867952618200515005539316960724088551539133626302522557345413249384658492371698805093289004717340532810196692880918816862832405941920828302568461913904088702147654713878056218117011839094769918168741678648022940613796829566893389100562532347981860917540264049

In [98]:
10 / 3

3.3333333333333335

In [99]:
75892745.215489247589274985712

75892745.21548925

In [100]:
75892745.215489247589274985712 - 75892745.21548925

0.0

In [101]:
(13 ** 0.5) ** 2

12.999999999999998

In [102]:
3.605551275463989 * 3.605551275463989

12.999999999999998

In [103]:
int(10 / 5)

2

In [104]:
int(10 / 4)

2

In [105]:
float(3)

3.0

In [106]:
6 / 4

1.5

In [107]:
6 / 4000

0.0015

In [108]:
6 / 400000000000000000000000000000000000000000000000000000000

1.5e-56

In [109]:
400000000000000000000000000000000000000000000000000000000 * 1.5e-56

6.0

In [110]:
1.5e-56

1.5e-56

In [111]:
x = 5

In [112]:
x

5

In [113]:
x + 1

6

In [114]:
# datascience
2x

SyntaxError: invalid decimal literal (1600826740.py, line 2)

In [115]:
# polars
2x

SyntaxError: invalid decimal literal (1466595064.py, line 2)

In [116]:
2 * x

10

## Longer Demo: Strings (Section 4.2)

(if time; otherwise try at home)

In [117]:
'Flavor'

'Flavor'

In [118]:
flavor = 2

In [119]:
flavor

2

In [120]:
# The line below causes a name error
# Flavor

In [121]:
"Flavor"

'Flavor'

In [122]:
# datascience
'Don't always use single quotes'

SyntaxError: unterminated string literal (detected at line 2) (3193896808.py, line 2)

In [123]:
# polars
'Don't always use single quotes'

SyntaxError: unterminated string literal (detected at line 2) (3171021756.py, line 2)

In [124]:
"Don't always use single quotes"

"Don't always use single quotes"

In [125]:
'straw' 'berry' # concatenation

'strawberry'

In [126]:
'straw' + 'berry' # concatenation

'strawberry'

In [127]:
'Chris' + 'Paul' # spaces aren't added for you

'ChrisPaul'

In [128]:
'Chris' + ' ' + 'Paul'

'Chris Paul'

In [129]:
x = 'straw'
y = 'berry'
x + y

'strawberry'

In [130]:
# datascience
x y

SyntaxError: invalid syntax (1536633515.py, line 2)

In [131]:
# polars
x y

SyntaxError: invalid syntax (171728815.py, line 2)

In [132]:
'ha' * 100

'hahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahaha'

In [133]:
# datascience
'lo' * 5.5

TypeError: can't multiply sequence by non-int of type 'float'

In [134]:
# polars
'lo' * 5.5

TypeError: can't multiply sequence by non-int of type 'float'

In [135]:
# datascience
'ha' + 10

TypeError: can only concatenate str (not "int") to str

In [136]:
# polars
'ha' + 10

TypeError: can only concatenate str (not "int") to str

In [137]:
'ha' + str(10)

'ha10'

In [138]:
'ha' + '10'

'ha10'

In [139]:
# datascience
'3' + 5

TypeError: can only concatenate str (not "int") to str

In [140]:
# polars
'3' + 5

TypeError: can only concatenate str (not "int") to str

In [141]:
int('3') + 5

8

In [142]:
# datascience
int('3.0')

ValueError: invalid literal for int() with base 10: '3.0'

In [143]:
# polars
int('3.0')

ValueError: invalid literal for int() with base 10: '3.0'

In [144]:
'3.0'

'3.0'

## Conversions

### Conversions between number types

In [145]:
int(10 / 5)

2

In [146]:
int(10 / 4)

2

In [147]:
float(3)

3.0

### Conversions with strings

In [148]:
float('3.0')

3.0

In [149]:
int(3.0)

3

In [150]:
int(float('3.0'))

3

In [151]:
3

3

In [152]:
dot_oh = '.0'
'3' + dot_oh

'3.0'

In [153]:
float('3' + dot_oh)

3.0

In [154]:
float('3' + dot_oh) * 7

21.0